#!/bin/sh

Help()
{
	echo "\e[32m\e[1m=====================\e[0m"
	echo "\e[32m\e[1m=    Information    =\e[0m"
	echo "\e[32m\e[1m=====================\e[0m\n"
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Android Backup"
	echo "\e[32m\e[1mCommand:\e[0m     android-backup"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.0.1.20201122\n"
	echo "\e[32m\e[1m================\e[0m"
	echo "\e[32m\e[1m=    Detail    =\e[0m"
	echo "\e[32m\e[1m================\e[0m\n"
	echo "You must execute the script with root permissions.\n"
	echo "This script permits to backup and restore the data and apps of an Android device.\nThe developer options must be activated on your device, the Android Debug Bridge must be activated too and your PC authorised."
	exit 0
}

Choice()
{
	echo "\n\e[32m\e[1m=======================\e[0m"
	echo "\e[32m\e[1mWhat do you want to do?\e[0m"
	echo "\e[32m\e[1m=======================\e[0m\n"
	echo "1 - Backup"
	echo "2 - Restore\n"
	echo "3 - Display backups\n"
	echo "4 - Exit\n"
	read -p "Your answer : " statement

	if [ $statement = "1" ]
	then
		if [ -d /home/"$name"/Backups/Android ]
		then
			Backup
		else
			mkdir /home/"$name"/Backups/Android
			Backup
		fi
	elif [ $statement = "2" ]
	then
		if [ -d /home/"$name"/Backups/Android ]
		then
			Restore
		else
			echo "The 'Android' folder does not exists on the disk. You have to create the folder and move your previous backup in it or make a backup in order to restore it.\n"
			exit 1
		fi
	elif [ $statement = "3" ]
	then
		ls -lsa /home/"$name"/Backups/Android
		Choice
	elif [ $statement = "4" ]
	then
		echo "\nExiting...\n"
		exit 0
	else
		echo "\nPlease select either '1', '2', '3' or '4'.\n"
		Choice
	fi
}

Backup()
{
	echo "\n\e[32m\e[1m======\e[0m"
	echo "\e[32m\e[1mBackup\e[0m"
	echo "\e[32m\e[1m======\e[0m\n"
	echo "Backup in progress...\n"
	adb backup -f -apk -all android-backup_$(date +%Y-%m-%d).ab  | pv -ptW >/dev/null
	mv android-backup_$(date +%Y-%m-%d).ab /home/"$name"/Backups/Android/
	echo "\nBackup over!\n"
	exit 0
}

Restore()
{
	echo "\n\e[32m\e[1m=======\e[0m"
	echo "\e[32m\e[1mRestore\e[0m"
	echo "\e[32m\e[1m=======\e[0m\n"
	read -p "Please type the archive date (YYYY-MM-DD) : " archive_date
	echo "\nRestore in progress...\n"
	adb restore /home/"$name"/Backups/Android/android-backup_"$archive_date".ab | pv -ptW >/dev/null
	echo "\nRestore over!\n"
	exit 0
}

name=0
statement=0

echo "\e[31m\e[1m****************\e[0m"
echo "\e[31m\e[1m*    BACKUP    *\e[0m"
echo "\e[31m\e[1m****************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	if [ "$(id -u)" != "0" ]
	then
	 	echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m\n" 1>&2
	 	exit 1
	else
		read -p "Please type your username : " name
		Choice
	fi
fi
