#!/bin/sh

Help()
{
	echo "\e[32m\e[1m=====================\e[0m"
	echo "\e[32m\e[1m=    Information    =\e[0m"
	echo "\e[32m\e[1m=====================\e[0m\n"
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Unlocker"
	echo "\e[32m\e[1mCommand:\e[0m     unlocker"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.3.0.20201119\n"
	echo "\e[32m\e[1m================\e[0m"
	echo "\e[32m\e[1m=    Detail    =\e[0m"
	echo "\e[32m\e[1m================\e[0m\n"
	echo "You must execute the script with root permissions.\n"
	echo "This script permits to unlock drives that are encrypted with Bitlocker using the 'dislocker' package.\nIt gives a R/W access to the unlocked drive.\n"
	exit 0
}

Confirmation()
{
	if [ $answer = "y" ] || [ $answer = "Y" ]
		then
      echo "\e[31m\e[1m/!\ The decrypted drive will be unmounted. Any unsaved activity on the drive will be lost. /!\\e[0m\n"
			read -p "Press any key to continue..." push1
      umount /media/"$name"/mount && umount /media/"$name"/bitlocker
      echo "\nThe folder and the drive has been unmounted.\n"
      exit 0
	elif [ $answer = "n" ] || [ $answer = "N" ]
		then
      echo "The folder and the drive are still mounted.\nTo unmount them, type the following commands : 'sudo umount /media/"$name"/mount && sudo umount /media/"$name"/bitlocker'\n"
      exit 0
	else
			echo "Please type 'y' or 'n'.\n"
	fi
}

Unlock()
{
	echo ""
	read -p "Enter the path of the drive to unlock : " path
	dislocker -V "$path" -u -- /media/"$name"/bitlocker
	mount -w -o loop /media/"$name"/bitlocker/dislocker-file /media/"$name"/mount
	Relock
}

Verification()
{
	if [ -d /media/"$name"/bitlocker ]
	then
		if [ -d /media/"$name"/mount ]
		then
			Unlock
		else
			mkdir /media/"$name"/mount
			Unlock
		fi
	else
		mkdir /media/"$name"/bitlocker
		if [ -d /media/"$name"/mount ]
		then
			Unlock
		else
			mkdir /media/"$name"/mount
			Unlock
		fi
	fi
}

Relock()
{
	echo ""
	read -p "Press any key to continue..." push0
	echo ""

	while [ $answer != "y" ] || [ $answer != "Y" ] || [ $answer != "n" ] || [ $answer != "N" ] || [ -z $answer ]
	do
		read -p "The script will now unmount the drive and the 'Bitlocker' folder, do you wish to continue ? ('y' or 'n') : " answer
		echo ""
		if [ $answer = 'y' ] || [ $answer = 'n' ]
		then
			break
		fi
	done

	if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
	then
		Confirmation
	else
		echo "An unsuspected error has occured.\n"
	fi
}

answer=0

echo "\e[31m\e[1m******************\e[0m"
echo "\e[31m\e[1m*    UNLOCKER    *\e[0m"
echo "\e[31m\e[1m******************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	if [ "$(id -u)" != "0" ]
		then
	   	echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m\n" 1>&2
	   	exit 1
		else
			read -p "Please type your username : " name
			Verification
	fi
fi
