#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  echo "*******************"
  echo "..::INFORMATION::.."
  echo "*******************"
  echo ""
  echo "Language:    EN-uk"
  echo "Script name: Update GIT"
  echo "Command:     update-git"
  echo "Author:      Kalvez"
  echo "Location:    /usr/bin/"
  echo "Version:     1.0.0.20191007"
  echo ""
  echo "**************"
  echo "..::DETAIL::.."
  echo "**************"
  echo ""
  echo "This script automatically updates the cloned GitHub repo of 'Scripts4Linux'."
  echo ""
  exit 0
fi

# Mise à zéro des arguments.
name=0
answer=0

# Déclaration de la fonction 'INSTALLATION'.
INSTALLATION()
{
	if [ $answer = "y" ] || [ $answer = "Y" ]
		then
      cd ~
      git clone http://github.com/kalvez/scripts4linux.git
      cd /scripts4linux
      chmod +x auto-installer/EN-uk
      sudo ./auto-installer
      echo ""
      exit
	elif [ $answer = "n" ] || [ $answer = "N" ]
		then
      echo "The scripts won't be updated."
      echo ""
      exit
	else
			echo "Please type 'y' or 'n'."
			echo ""
	fi
}

# Saisie et lecture du nom d'utilisateur.
read -p "Please type your username : " name
echo ""

# Vérification de la présence du dossier 'scripts4linux' sur le disque, et suppression s'il existe, puis clonage du repo GitHub.
if [ -d /home/"$name"/scripts4linux ]
then
 rm -rf /home/"$name"/scripts4linux
else
  cd /home/"$name"/
	git clone http://github.com/kalvez/scripts4linux.git
fi

# Installation des scripts.
read -p "Would you like to update the scripts now ? ('y' or 'n')" answer

if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
then
  INSTALLATION
else
  echo "An unsuspected error has occured."
fi
