#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  echo "\e[32m\e[1m*********************\e[0m"
  echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
  echo "\e[32m\e[1m*********************\e[0m"
  echo ""
  echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
  echo "\e[32m\e[1mScript name:\e[0m Upgrade"
  echo "\e[32m\e[1mCommand:\e[0m     upgrade"
  echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
  echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
  echo "\e[32m\e[1mVersion:\e[0m     1.2.2.20191022"
  echo ""
  echo "\e[32m\e[1m****************\e[0m"
  echo "\e[32m\e[1m*    DETAIL    *\e[0m"
  echo "\e[32m\e[1m****************\e[0m"
  echo ""
  echo "You must execute the script with root permissions."
  echo ""
  echo "This script updates the current linux distro.\nIt also cleans the update cache and remove the unused packages."
  echo ""
  exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
        then
        echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m" 1>&2
        echo ""
        exit 1
fi

echo "\e[32m\e[1m*****************\e[0m"
echo "\e[32m\e[1m*    UPGRADE    *\e[0m"
echo "\e[32m\e[1m*****************\e[0m"
echo ""

# MàJ de la distribution.
apt dist-upgrade

# Nettoyage des paquets inutilisés.
apt clean
apt autoremove -y
echo ""
echo "Linux distro update successful."
echo ""
