#!/bin/sh

Help()
{
  echo "\e[32m\e[1m=====================\e[0m"
  echo "\e[32m\e[1m=    Information    =\e[0m"
  echo "\e[32m\e[1m=====================\e[0m\n"
  echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
  echo "\e[32m\e[1mScript name:\e[0m Upgrade"
  echo "\e[32m\e[1mCommand:\e[0m     upgrade"
  echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
  echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
  echo "\e[32m\e[1mVersion:\e[0m     1.3.0.20201120\n"
  echo "\e[32m\e[1m================\e[0m"
  echo "\e[32m\e[1m=    Detail    =\e[0m"
  echo "\e[32m\e[1m================\e[0m\n"
  echo "You must execute the script with root permissions.\n"
  echo "This script updates the current linux distro.\nIt also cleans the update cache and remove the unused packages.\n"
  exit 0
}

Upgrade()
{
  apt-get dist-upgrade
  apt-get clean
  apt-get autoremove -y
  echo "\nLinux distro update successful.\n"
}

echo "\e[31m\e[1m*****************\e[0m"
echo "\e[31m\e[1m*    UPGRADE    *\e[0m"
echo "\e[31m\e[1m*****************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  Help
else
  if [ "$(id -u)" != "0" ]
    then
      echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m\n" 1>&2
      exit 1
    else
      Upgrade
  fi
fi
