#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "Langue : FR-fr"
	echo "Nom du script : Lat (pour 'Latency')"
	echo "Créateur : Kalvez"
	echo "Emplacement : /usr/bin/"
	echo "Date de la dernière version : 05 mars 2018"
	echo "Version : 1.0.3.20180305"
	echo ""
	echo ""
	echo "..::Détails::.."
	echo ""
	echo "Ce script permet d'afficher le délai de réponse entre la machine et le site 'google.com'."
	echo ""
	exit 0
fi

# Commande de ping.
ping www.google.com
