#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
        echo "Langue : FR-fr"
        echo "Nom du script : Upgrade"
        echo "Commande : upgrade"
        echo "Créateur : Kalvez"
        echo "Emplacement : /usr/bin/"
        echo "Date de la dernière version : 08 août 2019"
        echo "Version : 1.1.2.20190822"
        echo ""
        echo ""
        echo "..::Détails::.."
        echo ""
        echo "Vous devez exécuter ce script en tant qu'utilisateur root."
        echo "Ce script permet de mettre à jour la distribution linux actuelle. Il nettoie le cache de mise à jour."
        echo ""
        exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
        then
        echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
        echo ""
        exit 1
fi

# MàJ de la distribution.
apt dist-upgrade

# Nettoyage des paquets inutilisés.
apt autoremove
echo ""
echo "Mise à jour de la distribution Linux réussie."
echo ""
