#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "Langue : FR-fr"
	echo "Nom du script : Version"
	echo "Commande : version"
	echo "Créateur : Kalvez"
	echo "Emplacement : /usr/bin/"
	echo "Date de la dernière version : 05 mars 2018"
	echo "Version : 1.0.2.20180305"
	echo ""
	echo ""
	echo "..::Détails::.."
	echo ""
	echo "Ce script affiche la version actuelle de la distribution linux, ainsi que la version du noyeau."
	echo ""
	exit 0
fi

# Affichage de la verison de Linux et Debian.
lsb_release -a
uname -a
echo ""
