#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m*********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
	echo "\e[32m\e[1m*********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Archive"
	echo "\e[32m\e[1mCommand:\e[0m     archive [dossier/fichier] [dossier/fichier] [dossier/fichier] ..."
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     0.4.0.20191021-beta"
	echo ""
	echo "\e[32m\e[1m****************\e[0m"
	echo "\e[32m\e[1m*    DETAIL    *\e[0m"
	echo "\e[32m\e[1m****************\e[0m"
	echo ""
	echo "This script, which does not need any root privileges, permits to archive whatever you want in a '.zip' compressed folder.\nIt will ask for an archive name and then it will be saved with this name format : 'archive_name_year-month-day.zip'."
	echo ""
	exit 0
fi

# Déclaration des arguments.
args=0
files=$#

# Bandeau
echo "\e[32m\e[1m*****************\e[0m"
echo "\e[32m\e[1m*    ARCHIVE    *\e[0m"
echo "\e[32m\e[1m*****************\e[0m"
echo ""

# Lecture du nom donné à l'archive.
read -p "Archive name : " name
echo ""

# Script permettant d'archiver les fichiers et les dossiers dans une archive '.zip'.
for args in $*
do
	FICDOC=$1
	echo "Files or folders being archived : ${FICDOC}"
	echo ""
	if [ -f "${FICDOC}" ] || [ -d "${FICDOC}" ]
	then
		zip -r archive_"${name}"_$(date +%Y-%m-%d).zip "${FICDOC}" | pv -rbpteW >/dev/null
		echo ""
	else
		echo "Le file/folder ${FICDOC} does not exists."
		exit 1
	fi
	shift $(( args = ${args} + 1 )) 2>/dev/null
done
