#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "*******************"
	echo "..::INFORMATION::.."
	echo "*******************"
	echo ""
	echo "Language:    EN-uk"
	echo "Script name: Disks"
	echo "Command:     disks"
	echo "Author:      Kalvez"
	echo "Location:    /usr/bin/"
	echo "Version:     1.1.3.20190904"
	echo ""
	echo "**************"
	echo "..::DETAIL::.."
	echo "**************"
	echo ""
	echo "You must execute the script with root permissions."
	echo ""
	echo "This script displays each and every disks (internals, externals and partitions) and the flash medias connected to the computer and the total and remaning disk space."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
	then
   	echo "This script must be executed with root privileges." 1>&2
   	echo ""
   	exit 1
fi

fdisk -l
