#!/bin/sh

Help()
{
	echo "\e[32m\e[1m======================\e[0m"
	echo "\e[32m\e[1m=    Informations    =\e[0m"
	echo "\e[32m\e[1m======================\e[0m\n"
	echo "\e[32m\e[1mLangue:\e[0m        FR-fr"
	echo "\e[32m\e[1mNom du script:\e[0m Speed"
	echo "\e[32m\e[1mCommande:\e[0m      speed"
	echo "\e[32m\e[1mCréateur:\e[0m      Kalvez"
	echo "\e[32m\e[1mEmplacement:\e[0m   /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m       1.1.0.20200801\n"
	echo "\e[32m\e[1m=================\e[0m"
	echo "\e[32m\e[1m=    Détails    =\e[0m"
	echo "\e[32m\e[1m=================\e[0m\n"
	echo "Basé sur le programme en ligne de commande 'speedtest-cli', ce programme permet de tester la connexion internet de votre réseau.\nIl dispose d'une connexion sécurisée (--secure) et utilise les MB et non les Mb (--bytes).\n"
	exit 0
}

Speed()
{
	echo "\e[32m\e[1m=========================\e[0m"
	echo "\e[32m\e[1m=    Speedtesting...    =\e[0m"
	echo "\e[32m\e[1m=========================\e[0m\n"

	speedtest --bytes --secure

	echo "\nSpeedtesting terminé !\n"
}

echo "\e[31m\e[1m***************\e[0m"
echo "\e[31m\e[1m*    SPEED    *\e[0m"
echo "\e[31m\e[1m***************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	Speed
	#echo "\n"
fi
