#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m*********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
	echo "\e[32m\e[1m*********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Backup"
	echo "\e[32m\e[1mCommand:\e[0m     backup"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.6.1.20200508"
	echo ""
	echo "\e[32m\e[1m****************\e[0m"
	echo "\e[32m\e[1m*    DETAIL    *\e[0m"
	echo "\e[32m\e[1m****************\e[0m"
	echo ""
	echo "You must execute the script with root permissions."
	echo ""
	echo "This script permits to backup the following folders : '/etc/', 'Documents', 'Pictures' and 'Download' in a '.tar' archive automatically named 'backup' and dated according to the date of the day.\nOnce the archive is created, it's placed in the 'Backups' folder located in your personnal folder.\nIf it's not present on the disk, it will automatically be created is the user folder. In your case, this will be in the '/home/$USER/' folder.\nThis script is using the '.tar' archive format which is a proprietary format. However, if you want to modify the backupped folder in the archive, you can edit that script at the line 40 and put whatever you want to backup respecting the spaces between each argument."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
then
 	echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m" 1>&2
 	echo ""
 	exit 1
fi

# Fonction de compression.
Backup()
{
	# Création de l'archive
	tar -c --use-compress-program=pigz -vf backup_$(date +%Y-%m-%d).tar /etc/ /home/"$name"/Documents/ /home/"$name"/Pictures/ /home/"$name"/Downloads/ | pv -ptW >/dev/null
	mv backup_$(date +%Y-%m-%d).tar /home/"$name"/Backups/
}

echo "\e[32m\e[1m****************\e[0m"
echo "\e[32m\e[1m*    BACKUP    *\e[0m"
echo "\e[32m\e[1m****************\e[0m"
echo ""

# Saisie et lecture du nom d'utilisateur.
read -p "Please type your username : " name
echo ""

# Vérification de la présence du dossier 'Backups' sur le disque, et création du dossier s'il n'existe pas.
if [ -d /home/"$name"/Backups ]
then
	Backup
else
	mkdir /home/"$name"/Backups/
	Backup
fi

echo ""
echo "Backup over !"
echo ""
