#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "*********************"
	echo "*    INFORMATION    *"
	echo "*********************"
	echo ""
	echo "Language:    EN-uk"
	echo "Script name: Backup"
	echo "Command:     backup"
	echo "Author:      Kalvez"
	echo "Location:    /usr/bin/"
	echo "Version:     1.7.O.20200523"
	echo ""
	echo "****************"
	echo "*    DETAIL    *"
	echo "****************"
	echo ""
	echo "You must execute the script with root permissions."
	echo ""
	echo "This script permits to backup the following folders : 'Documents', 'Pictures' and 'Download' in a '.tar' archive automatically named 'backup' and dated according to the date of the day.\nOnce the archive is created, it's placed in the 'Backups' folder located in your personnal folder.\nIf it's not present on the disk, it will automatically be created is the user folder. In your case, this will be in the '/home/$USER/' folder.\nThis script is using the '.tar' archive format which is a proprietary format. However, if you want to modify the backupped folder in the archive, you can edit that script at the line 41 and put whatever you want to backup respecting the spaces between each argument.\nTo restore a backup, you have to create the 'Backups' folder in the root of your personal folder, if it does not already exists, and place the backup archive in 'Backups'."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
then
 	echo "\e[31m\e[1mThis script must be executed with root privileges." 1>&2
 	echo ""
 	exit 1
fi

# Fonction de compression.
Backup()
{
	# Création de l'archive.
	echo "Backup in progress..."
	tar -c --use-compress-program=pigz -vf backup_$(date +%Y-%m-%d).tar /home/"$name"/Documents/ /home/"$name"/Images/ /home/"$name"/Téléchargements/ | pv -ptW >/dev/null
	mv backup_$(date +%Y-%m-%d).tar /home/"$name"/Backups/

	echo ""
	echo "Backup over!"
	echo ""
	exit 0
}

# Fonction de décompression.
Restore()
{
	# Saisie et lecture de la date de l'archive.
	read -p "Please type the archive date (YYYY-MM-DD) : " archive_date
	echo ""

	# Extraction de l'archive.
	echo "Restore in progress..."
	tar -xvzf /home/"$name"/Backups/backup_"$archive_date".tar -C / | pv -ptW >/dev/null
	sudo chown -R $name: /home/"$name"/

	echo ""
	echo "Restore over!"
	echo ""
	exit 0
}

echo "****************"
echo "*    BACKUP    *"
echo "****************"
echo ""

# Saisie et lecture du nom d'utilisateur.
read -p "Please type your username : " name
echo ""

echo "What do you want to do?"
echo "1 - Backup"
echo "2 - Restore"
echo ""
read -p "Your answer : " statement
echo ""

if [ $statement = 1 ]
then
	# Vérification de la présence du dossier 'Backups' sur le disque, et création du dossier s'il n'existe pas.
	if [ -d /home/"$name"/Backups ]
	then
		Backup
	else
		mkdir /home/"$name"/Backups/
		Backup
	fi
elif [ $statement = 2 ]
then
	if [ -d /home/"$name"/Backups ]
	then
		Restore
	else
		echo "The 'Backups' folder does not exists on the disk. You have to create a backup in order to restore it."
		exit 1
	fi
else
	echo "Please select either '1' or '2'."
	echo ""
	sudo backup
fi
