#!/bin/sh

Help()
{
	echo "\e[32m\e[1m=====================\e[0m"
	echo "\e[32m\e[1m=    Information    =\e[0m"
	echo "\e[32m\e[1m=====================\e[0m\n"
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Disks"
	echo "\e[32m\e[1mCommand:\e[0m     disks"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.4.0.20200506\n"
	echo "\e[32m\e[1m================\e[0m"
	echo "\e[32m\e[1m=    Detail    =\e[0m"
	echo "\e[32m\e[1m================\e[0m\n"
	echo "You must execute the script with root permissions if you want to access the advanced display.\n"
	echo "This script displays each and every disks (internals, externals and partitions) and the flash medias connected to the computer and the total and remaning disk space.\n The '-a' or '--advanced' arguments display the advanced drive list.\n"
	exit 0
}

Advanced()
{
	echo "\e[32m\e[1m==================\e[0m"
	echo "\e[32m\e[1m=    Advanced    =\e[0m"
	echo "\e[32m\e[1m==================\e[0m\n"
	fdisk -l
}

Basic()
{
	df -h
}

echo "\e[31m\e[1m***************\e[0m"
echo "\e[31m\e[1m*    DISKS    *\e[0m"
echo "\e[31m\e[1m***************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
elif [ $1 = "-a" 2>/dev/null ] || [ $1 = "--advanced" 2>/dev/null ]
then
	if [ "$(id -u)" != "0" ]
	then
		echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m\n" 1>&2
		exit 1
	else
		Advanced
	fi
else
	Basic
fi
