#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
        echo "Langue : FR-fr"
        echo "Nom du script : Restore Firefox ESR"
        echo "Commande : restore-firefox-esr"
        echo "Créateur : Kalvez"
        echo "Emplacement : /usr/bin/"
        echo "Date de la dernière version : 15 février 2019"
        echo "Version : 1.2.1.20190215"
        echo ""
        echo ""
        echo "..::Détails::.."
        echo ""
        echo "Ce script désinstalle Firefox Quantum et le remplace par le navigateur Firefox de base : Firefox ESR."
        echo ""
        exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
then
        echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
        echo ""
        exit 1
fi

read -p "Voulez-vous vraiment supprimer Firefox Quantum et tous ses composants ? (y ou n) : " answer

if [ $answer = "y" ]
then
        # Demande du nom d'utilisateur.
        read -p "Pour le bon déroulement de la suppression de Mozilla Firefox Quantum, veuillez taper votre nom d'utilisateur : " name
        echo ""
        
        # Suppression du lien symbolique entre Firefox Quantum et Firefox ESR.
        unlink /usr/lib/firefox-esr/firefox-esr
        
        # Restauration de Firefox-ESR
        mv /usr/lib/firefox-esr/firefox-esr_orig /usr/lib/firefox-esr/firefox-esr
        
        # Suppression du dossier de Firefox Quantum.
        rm -rf /opt/firefox
        
        # Suppression de ce qui reste de Firefox Quantum.
        rm /usr/bin/get-firefox
        rm /usr/bin/update-firefox
        rm /usr/bin/remove-firefox-install-package
        rm -rf /home/"$name"/Images/.firefox_quantum_icons
        echo ""
        echo "Firefox ESR a été restauré avec succès, veuillez exécuter un 'apt-get update' (ou 'apt update')."
        echo "Pour réinstaller Firefox Quantum, veuillez passer par le script 'install-scripts'."
        echo ""
        exit 0
elif [ $answer = "n" ]
then
        echo "La désinatallation de Firefox Quantum a été abandonnée."
        echo ""
else
        echo "Veuillez taper 'y' ou 'n'."
        echo ""
        restore-firefox-esr
fi

# Changement des noms de Firefox Quantum vers Firefox ESR.
rm /usr/share/applications/firefox-esr.desktop
mv /usr/share/applications/firefox-esr.desktop.old /usr/share/applications/firefox-esr.desktop
