#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "Langue : FR-fr"
	echo "Nom du script : Update Firefox"
	echo "Commande : update-firefox"
	echo "Créateur : Kalvez"
	echo "Emplacement : /usr/bin/"
	echo "Date de la dernière version : 22 mars 2018"
	echo "Version : 1.5.0.20180322"
	echo ""
	echo ""
	echo "..::Détails::.."
	echo ""
	echo "Ce script permet de mettre à jour le navigateur internet Mozilla Firefox Quantum, le remplacent"
	echo "de Mozilla Firefox ESR (Extended Support Release). Ce script va chercher le paquet d'installation"
	echo "de Firefox Quantum dans les dépôts officiels de Mozilla."
	echo "De plus, il fait appel aux scripts 'change-firefox-icon' et 'remove-firefox-install-package' qui"
	echo "permettent de changer les icônes de base de Firefox ESR pour celles de Firefox Quantum, et de"
	echo "supprimer du disque le paquet d'installation de Firefox."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
        then
        echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
        echo ""
        exit 1
fi

# Demande du nom d'utilisateur.
read -p "Pour le bon déroulement de la mise à jour de Mozilla Firefox Quantum, veuillez taper votre nom d'utilisateur : " name
echo ""

# Téléchargement du paquet d'installation de Firefox Quantum et installation de la MàJ.
wget -O FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
tar xjf FirefoxSetup.tar.bz2 -C /opt/firefox/


# Copie des icônes vers les dossiers où sont stockées les icônes dans le système.
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-16.png /usr/share/icons/hicolor/16x16/apps/firefox-esr.png
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-symbolic.svg /usr/share/icons/hicolor/symbolic/apps/firefox-esr-symbolic.svg
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-32.png /usr/share/icons/hicolor/32x32/apps/firefox-esr.png
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-48.png /usr/share/icons/hicolor/48x48/apps/firefox-esr.png
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-64.png /usr/share/icons/hicolor/64x64/apps/firefox-esr.png
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-128.png /usr/share/icons/hicolor/128x128/apps/firefox-esr.png

# Changement des noms de Firefox ESR vers Firefox Quantum.
mv /usr/share/applications/firefox-esr.desktop /usr/share/applications/firefox-esr.desktop.old
cp /home/"$name"/Documents/.firefox_name_files/firefox-esr.desktop /usr/share/applications/

# Suppression du paquet d'installation de Firefox Quantum.
remove-firefox-install-package
echo ""
echo "Firefox a été mis à jour."
echo ""
