#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  echo "********************"
  echo "..::INFORMATIONS::.."
  echo "********************"
  echo ""
  echo "Langue:         FR-fr"
  echo "Nom du script:  Update"
  echo "Commande:       update"
  echo "Créateur:       Kalvez"
  echo "Emplacement:    /usr/bin/"
  echo "Version:        1.5.4.20190904"
  echo ""
  echo "***************"
  echo "..::DÉTAILS::.."
  echo "***************"
  echo ""
  echo "Vous devez exécuter ce script en tant qu'utilisateur root."
  echo ""
  echo "Ce script permet de mettre à jour les dépôts et les paquets des logiciels installés.\nIl nettoie aussi le cache des mises à jour et les paquets inutilisés."
  echo ""
  exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
        then
        echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
        echo ""
        exit 1
fi

# Mise à jour et confirmation automatique.
apt -y update

# Mise à jour des autres paquets et confirmation automatique.
apt -y full-upgrade

# Nettoyage des paquets inutilisés.
apt clean
apt -y autoremove
echo ""
echo "Mise à jour réussie."
echo ""
