#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m*********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
	echo "\e[32m\e[1m*********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Disks"
	echo "\e[32m\e[1mCommand:\e[0m     disks"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.3.0.20200409"
	echo ""
	echo "\e[32m\e[1m****************\e[0m"
	echo "\e[32m\e[1m*    DETAIL    *\e[0m"
	echo "\e[32m\e[1m****************\e[0m"
	echo ""
	echo "You must execute the script with root permissions if you want to access the advanced display."
	echo ""
	echo "This script displays each and every disks (internals, externals and partitions) and the flash medias connected to the computer and the total and remaning disk space.\n The "-a" or "--advanced" arguments display the advanced drive list."
	echo ""
	exit 0
fi

# Choix de l'affichage
if [ $1 = "-a" 2>/dev/null ] || [ $1 = "--advanced" 2>/dev/null ]
then
	# Vérification des privilèges root de l'utilisateur.
	if [ "$(id -u)" != "0" ]
		then
	   	echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m" 1>&2
	   	echo ""
	   	exit 1
	fi
	echo "\e[32m\e[1m***************\e[0m"
	echo "\e[32m\e[1m*    DISKS    *\e[0m"
	echo "\e[32m\e[1m***************\e[0m"
	echo ""

	fdisk -l
else
	echo "\e[32m\e[1m***************\e[0m"
	echo "\e[32m\e[1m*    DISKS    *\e[0m"
	echo "\e[32m\e[1m***************\e[0m"
	echo ""

	df -h
fi
