#!/bin/sh

Help()
{
	echo "\e[32m\e[1m=====================\e[0m"
	echo "\e[32m\e[1m=    Information    =\e[0m"
	echo "\e[32m\e[1m=====================\e[0m\n"
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Lat (for 'Latency')"
	echo "\e[32m\e[1mCommand:\e[0m     lat"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.1.0.20200801\n"
	echo "\e[32m\e[1m================\e[0m"
	echo "\e[32m\e[1m=    Detail    =\e[0m"
	echo "\e[32m\e[1m================\e[0m\n"
	echo "This script displays the repsonse time between the PC and Google's DNS.\n"
	exit 0
}

Ping()
{
	echo "\e[32m\e[1m==========================\e[0m"
	echo "\e[32m\e[1m=    Ping (Google DNS)   =\e[0m"
	echo "\e[32m\e[1m==========================\e[0m\n"

	ping 8.8.8.8
}

echo "\e[31m\e[1m*************\e[0m"
echo "\e[31m\e[1m*    LAT    *\e[0m"
echo "\e[31m\e[1m*************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	Ping
fi
