#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m*********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
	echo "\e[32m\e[1m*********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Lat (for 'Latency')"
	echo "\e[32m\e[1mCommand:\e[0m     lat"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.0.5.201909021"
	echo ""
	echo "\e[32m\e[1m****************\e[0m"
	echo "\e[32m\e[1m*    DETAIL    *\e[0m"
	echo "\e[32m\e[1m****************\e[0m"
	echo ""
	echo "This script displays the repsonse time between the PC and Google's DNS."
	echo ""
	exit 0
fi

echo "\e[32m\e[1m*************\e[0m"
echo "\e[32m\e[1m*    LAT    *\e[0m"
echo "\e[32m\e[1m*************\e[0m"
echo ""

# Commande de ping.
ping 8.8.8.8
