#!/bin/sh

Help()
{
  echo "\e[32m\e[1m=====================\e[0m"
  echo "\e[32m\e[1m=    Information    =\e[0m"
  echo "\e[32m\e[1m=====================\e[0m\n"
  echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
  echo "\e[32m\e[1mScript name:\e[0m Update GIT"
  echo "\e[32m\e[1mCommand:\e[0m     update-git"
  echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
  echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
  echo "\e[32m\e[1mVersion:\e[0m     1.1.0.20201120\n"
  echo "\e[32m\e[1m================\e[0m"
  echo "\e[32m\e[1m=    Detail    =\e[0m"
  echo "\e[32m\e[1m================\e[0m\n"
  echo "You must execute the script with root permissions.\n"
  echo "This script automatically updates the cloned GitHub repo of 'scripts4linux'.\n"
  exit 0
}

Update()
{
  if [ -d /home/"$name"/scripts4linux ]
  then
    rm -rf /home/"$name"/scripts4linux
    cd /home/"$name"/
    git clone http://github.com/kalvez/scripts4linux.git
    echo ""
  else
    cd /home/"$name"/
  	git clone http://github.com/kalvez/scripts4linux.git
    echo ""
  fi
}

Installation()
{
	if [ $answer = "y" ] || [ $answer = "Y" ]
		then
      chmod +x /home/"$name"/scripts4linux/EN-uk/auto-installer
      cd /home/"$name"/scripts4linux/EN-uk && ./auto-installer
      echo ""
      exit 0
	elif [ $answer = "n" ] || [ $answer = "N" ]
		then
      echo "The scripts won't be updated.\n"
      exit 0
	else
			echo "Please type 'y' or 'n'.\n"
	fi
}

name=0
answer=0

echo "\e[31m\e[1m********************\e[0m"
echo "\e[31m\e[1m*    UPDATE GIT    *\e[0m"
echo "\e[31m\e[1m********************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  Help
fi

if [ "$(id -u)" != "0" ]
  then
    echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m\n" 1>&2
    exit 1
  else
    read -p "Please type your username : " name
    echo ""
    Update
    read -p "Would you like to update the scripts now ? ('y' or 'n') : " answer
    echo ""
    if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
    then
      Installation
      echo ""
    else
      echo "An unsuspected error has occured.\n"
    fi
fi
