#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "********************"
	echo "..::INFORMATIONS::.."
	echo "********************"
	echo ""
	echo "Langue:        FR-fr"
	echo "Nom du script: Archive"
	echo "Commande:      archive [dossier/fichier] [dossier/fichier] [dossier/fichier] ..."
	echo "Créateur:      Kalvez"
	echo "Emplacement:   /usr/bin/"
	echo "Version:       0.3.6.20190904-beta"
	echo ""
	echo "***************"
	echo "..::DÉTAILS::.."
	echo "***************"
	echo ""
	echo "Ce script, qui ne demande aucun privilèges particulier, permet d'archiver dans des fichiers '.zip' ce que vous souhaitez, que ça soit des dossiers ou des fichiers.\nIl vous demandera alors un nom d'archive, alors il enregistrera l'archive au format suivant : 'archive_nom_année-mois-jour.zip'."
	echo ""
	exit 0
fi

# Déclaration des arguments.
args=0
files=$#

# Lecture du nom donné à l'archive.
read -p "Nom de l'archive: " name
echo ""

# Script permettant d'archiver les fichiers et les dossiers dans une archive '.zip'.
for args in $*
do
	FICDOC=$1
	echo "Fichiers ou dossiers en cours de traitement : ${FICDOC}"
	echo ""
	if [ -f "${FICDOC}" ] || [ -d "${FICDOC}" ] | pv -rbpteW >/dev/null
	then
		zip -r archive_"${name}"_$(date +%Y-%m-%d).zip "${FICDOC}"
		echo ""
	else
		echo "Le fichier/dossier ${FICDOC} n'existe pas."
		exit 1
	fi
	shift $(( args = ${args} + 1 )) 2>/dev/null
done
