#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "********************"
	echo "..::INFORMATIONS::.."
	echo "********************"
	echo ""
	echo "Langue:        FR-fr"
	echo "Nom du script: Backup"
	echo "Commande:      backup"
	echo "Créateur:      Kalvez"
	echo "Emplacement:   /usr/bin/"
	echo "Version:       1.4.6.20191008"
	echo ""
	echo "***************"
	echo "..::DÉTAILS::.."
	echo "***************"
	echo ""
	echo "Vous devez exécuter ce script en tant qu'utilisateur root."
	echo ""
	echo "Ce script permet de sauvegarder les dossiers 'Documents', 'Images' et 'Téléchargements' dans une archive '.zip' automatiquement nommée 'backup' et datée en fonction de la date de la sauvegarde.\nCette archive est ensuite déplacée dans le dossier 'Backups' situé dans votre dossier personnel.\nSi celui-ci n'est pas présent sur le disque, il sera automatiquement créé dans le dossier de l'utilisateur. Dans votre cas, ça sera dans le dossier '/home/$USER/'.\nCe script utilise le format d'archivage '.zip' qui est propriétaire donc non-libre de droits. Si toutefois vous souhaitez modifier les dossiers sauvegardés dans l'archive '.zip', vous pouvez éditer le script à la ligne 58 juste après la commande d'archivage et mettre la localisation des dossiers que vous souhaitez sauvegarder tout en respectant l'interval d'un espace entre chaque dossier voulu."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
	then
   	echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
   	echo ""
   	exit 1
fi

# Saisie et lecture du nom d'utilisateur.
read -p "Saisissez votre nom d'utilisateur : " name
echo ""

# Vérification de la présence du dossier 'Backups' sur le disque, et création du dossier s'il n'existe pas.
if [ -d /home/"$name"/Backups ]
then
	echo "Le dossier 'Backups' existe déjà."
	echo ""
else
	echo "Le dossier 'Backups' n'existe pas encore et va être créé dans le répertoire '/home/"$name"/'."
	echo ""
	mkdir /home/"$name"/Backups/

	if [ -d /home/"$name"/Backups ]
	then
		echo "Le dossier à bien été créé."
		echo ""
	fi
fi

# Création de l'archive
zip -r backup_$(date +%Y-%m-%d).zip /etc/ /home/"$name"/Documents/ /home/"$name"/Images/ /home/"$name"/Téléchargements/ | pv -rbpteW >/dev/null
mv backup_$(date +%Y-%m-%d).zip /home/"$name"/Backups/

echo ""
echo "Sauvegarde terminée !"
echo ""
