#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  echo "\e[32m\e[1m**********************\e[0m"
  echo "\e[32m\e[1m*    INFORMATIONS    *\e[0m"
  echo "\e[32m\e[1m**********************\e[0m"
  echo ""
  echo "\e[32m\e[1mLangue:\e[0m         FR-fr"
  echo "\e[32m\e[1mNom du script:\e[0m  Update GIT"
  echo "\e[32m\e[1mCommande:\e[0m       update-git"
  echo "\e[32m\e[1mCréateur:\e[0m       Kalvez"
  echo "\e[32m\e[1mEmplacement:\e[0m    /usr/bin/"
  echo "\e[32m\e[1mVersion:\e[0m        1.0.1.20191021"
  echo ""
  echo "\e[32m\e[1m*****************\e[0m"
  echo "\e[32m\e[1m*    DÉTAILS    *\e[0m"
  echo "\e[32m\e[1m*****************\e[0m"
  echo ""
  echo "Vous devez exécuter ce script en tant qu'utilisateur root."
  echo ""
  echo "Ce script met à jour le dépôt local clôné de 'scripts4linux'."
  echo ""
  exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
  then
    echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m" 1>&2
    echo ""
    exit 1
fi

echo "\e[32m\e[1m********************\e[0m"
echo "\e[32m\e[1m*    UPDATE GIT    *\e[0m"
echo "\e[32m\e[1m********************\e[0m"
echo ""

# Mise à zéro des arguments.
name=0
answer=0

# Déclaration de la fonction 'INSTALLATION'.
INSTALLATION()
{
	if [ $answer = "y" ] || [ $answer = "Y" ]
		then
      cd /home/"$name"/scripts4linux/FR-fr/
      chmod +x auto-installer
      ./auto-installer
      echo ""
      exit
	elif [ $answer = "n" ] || [ $answer = "N" ]
		then
      echo "Les scripts ne seront pas mis à jour."
      echo ""
      exit
	else
			echo "Veuillez appuyer sur 'y' ou 'n'."
			echo ""
	fi
}

# Saisie et lecture du nom d'utilisateur.
read -p "Saisissez votre nom d'utilisateur : " name
echo ""

# Vérification de la présence du dossier 'scripts4linux' sur le disque, et suppression s'il existe, puis clonage du repo GitHub.
if [ -d /home/"$name"/scripts4linux ]
then
  rm -rf /home/"$name"/scripts4linux
  cd /home/"$name"/
  git clone http://github.com/kalvez/scripts4linux.git
  echo ""
else
  cd /home/"$name"/
	git clone http://github.com/kalvez/scripts4linux.git
  echo ""
fi

# Installation des scripts.
read -p "Voulez-vous mettre les scripts à jour maintenant ? ('y' or 'n') : " answer
echo ""

if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
then
  INSTALLATION
else
  echo "Une erreur inattendue est survenue."
  echo ""
fi
