#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  echo "********************"
  echo "..::INFORMATIONS::.."
  echo "********************"
  echo ""
  echo "Langue:         FR-fr"
  echo "Nom du script:  Upgrade"
  echo "Commande:       upgrade"
  echo "Créateur:       Kalvez"
  echo "Emplacement:    /usr/bin/"
  echo "Version:        1.2.1.20190904"
  echo ""
  echo "***************"
  echo "..::DÉTAILS::.."
  echo "***************"
  echo ""
  echo "Vous devez exécuter ce script en tant qu'utilisateur root."
  echo ""
  echo "Ce script permet de mettre à jour la distribution linux actuelle.\nIl nettoie le cache de mise à jour et supprime les paquets inutilisés."
  echo ""
  exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
        then
        echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
        echo ""
        exit 1
fi

# MàJ de la distribution.
apt dist-upgrade

# Nettoyage des paquets inutilisés.
apt clean
apt -y autoremove
echo ""
echo "Mise à jour de la distribution Linux réussie."
echo ""
