#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "*******************"
	echo "..::INFORMATION::.."
	echo "*******************"
	echo ""
	echo "Language:    EN-uk"
	echo "Script name: Automatic script installer for Debian and Kali Linux."
	echo "Command:     auto-installer"
	echo "Author:      Kalvez"
	echo "Location:    scripts4linux/EN-uk/"
	echo "Version:     2.5.1.20190904"
	echo ""
	echo "**************"
	echo "..::DETAIL::.."
	echo "**************"
	echo ""
	echo "/!\ This script must be executed with root permissions /!\ "
	echo ""
	echo "This script detects the Linux distro on which it's running and chooses the right script pack to install."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
	then
	echo "This script must be executed with root permissions." 1>&2
	echo ""
	exit 1
fi

echo "**************"
echo "AUTO-INSTALLER"
echo "**************"

# Vérification de la version de Linux.
if [ -z "$(lsb_release -a 2>/dev/null | grep Debian)" ]
then
	if [ -z "$(lsb_release -a 2>/dev/null | grep Kali)" ]
	then
		if [ -z "$(lsb_release -a 2>/dev/null | grep Ubuntu)" ]
		then
			if [ -z "$(lsb_release -a 2>/dev/null | grep elementary)" ]
			then
				if [ -z "$(lsb_release -a 2>/dev/null | grep LinuxMint)" ]
				then
					if [ -z "$(lsb_release -a 2>/dev/null | grep ManjaroLinux)" ]
					then
						echo "Please use an appropriate distro."
					else
						cd Manjaro\ -\ Mandriva/
						chmod +x installer
						./installer
						exit 0
					fi
				else
					cd Linux\ Mint/
					chmod +x installer
					./installer
					exit 0
				fi
			else
				cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS/
				chmod +x installer
				./installer
				exit 0
			fi
		else
			cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS/
			chmod +x installer
			./installer
			exit 0
		fi
	else
		cd Debian\ -\ Kali\ Linux/
		chmod +x installer
		./installer
		exit 0
	fi
else
  cd Debian\ -\ Kali\ Linux/
  chmod +x installer
  ./installer
  exit 0
fi
