#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m*********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
	echo "\e[32m\e[1m*********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Automatic script installer for Debian and Kali Linux."
	echo "\e[32m\e[1mCommand:\e[0m     auto-installer"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    scripts4linux/EN-uk/"
	echo "\e[32m\e[1mVersion:\e[0m     2.5.5.20200622"
	echo ""
	echo "\e[32m\e[1m****************\e[0m"
	echo "\e[32m\e[1m*    DETAIL    *\e[0m"
	echo "\e[32m\e[1m****************\e[0m"
	echo ""
	echo "/!\ This script must be executed with root permissions /!\ "
	echo ""
	echo "This script detects the Linux distro on which it's running and chooses the right script pack to install."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
	then
	echo "\e[31m\e[1mThis script must be executed with root permissions.\e[0m" 1>&2
	echo ""
	exit 1
fi

echo "\e[32m\e[1m************************\e[0m"
echo "\e[32m\e[1m*    AUTO INSTALLER    *\e[0m"
echo "\e[32m\e[1m************************\e[0m"
echo ""

# Vérification de la version de Linux.
if [ -z "$(lsb_release -a 2>/dev/null | grep Debian)" ]
then
	if [ -z "$(lsb_release -a 2>/dev/null | grep Raspbian)" ]
	then
		if [ -z "$(lsb_release -a 2>/dev/null | grep Kali)" ]
		then
			if [ -z "$(lsb_release -a 2>/dev/null | grep Ubuntu)" ]
			then
				if [ -z "$(lsb_release -a 2>/dev/null | grep elementary)" ]
				then
					if [ -z "$(lsb_release -a 2>/dev/null | grep LinuxMint)" ]
					then
						if [ -z "$(lsb_release -a 2>/dev/null | grep ManjaroLinux)" ]
						then
							if [ -z "$(lsb_release -a 2>/dev/null | grep Zorin)" ]
							then
								if [ -z "$(lsb_release -a 2>/dev/null | grep Deepin)" ]
								then
									if [ -z "$(lsb_release -a 2>/dev/null | grep Pop)" ]
									then
										echo "Please use an appropriate distro."
									else
										cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
										chmod +x installer
										./installer
										exit 0
									fi
								else
									cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
									chmod +x installer
									./installer
									exit 0
								fi
							else
								cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
								chmod +x installer
								./installer
								exit 0
							fi
						else
							cd Manjaro\ -\ Mandriva/
							chmod +x installer
							./installer
							exit 0
						fi
					else
						cd Linux\ Mint/
						chmod +x installer
						./installer
						exit 0
					fi
				else
					cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
					chmod +x installer
					./installer
					exit 0
				fi
			else
				cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
				chmod +x installer
				./installer
				exit 0
			fi
		else
			cd Debian\ -\ Kali\ Linux/
			chmod +x installer
			./installer
			exit 0
		fi
	else
		cd Raspbian/
		chmod +x installer
		./installer
		exit 0
	fi
else
  cd Debian\ -\ Kali\ Linux/
  chmod +x installer
  ./installer
  exit 0
fi
