#!/bin/sh

Help()
{
	echo "\e[32m\e[1m=====================\e[0m"
	echo "\e[32m\e[1m=    Information    =\e[0m"
	echo "\e[32m\e[1m=====================\e[0m\n"
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Speed"
	echo "\e[32m\e[1mCommand:\e[0m     speed"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.1.0.20200801\n"
	echo "\e[32m\e[1m================\e[0m"
	echo "\e[32m\e[1m=    Detail    =\e[0m"
	echo "\e[32m\e[1m================\e[0m\n"
	echo "Based on the 'speedtest-cli' package, this script tests your network's internet connection.\nIt has a secure connection (--secure) and uses 'MB' instead of 'Mb' (--bytes).\n"
	exit 0
}

Speed()
{
	echo "\e[32m\e[1m=========================\e[0m"
	echo "\e[32m\e[1m=    Speedtesting...    =\e[0m"
	echo "\e[32m\e[1m=========================\e[0m\n"

	speedtest --bytes --secure

	echo "\nSpeedtesting over!\n"
}

echo "\e[31m\e[1m***************\e[0m"
echo "\e[31m\e[1m*    SPEED    *\e[0m"
echo "\e[31m\e[1m***************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	Speed
fi
