#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "Langue : FR-fr"
	echo "Nom du script : Installeur de scripts pour Debian"
	echo "Commande : install-scripts"
	echo "Créateur : Kalvez"
	echo "Emplacement : /usr/bin/"
	echo "Date de la dernière version : 15 février 2018"
	echo "Version : 2.0.1.20190215"
	echo ""
	echo ""
	echo "..::Détails::.."
	echo ""
	echo "Vous devez exécuter ce script en tant qu'utilisateur root."
	echo ""
	echo "Ce script permet d'installer les scripts suivant dans le dossier '/usr/bin/',"
	echo "ainsi que leurs dépendances (à savoir 'speedtest-cli' et 'zip'. Ces scripts sont :"
	echo "'archive', 'backup', 'disks', 'lat', 'speed', 'update', 'upgrade', 'version'"
	echo "et toute la suite de scripts nécéssaires à l'installation de Firefox Quantum"
	echo "tels que 'get-firefox', 'update-firefox', 'remove-firefox-install-package'"
	echo "et 'restore-firefox'."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
	then
	echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
	echo ""
	exit 1
fi

# Lancement du script en lui-même.
echo ""
echo "..::INSTALLEUR DE SCRIPTS POUR LINUX::.."
echo ""

echo "Souhaitez-vous installer tous les scripts d'un coup ('y'), ou choisir individuellement les scripts à installer ('n') ?"
echo "/!\ ATTENTION : Ceci ('y') entraînera l'installation automatique des paquets nécessaires ('speedtest-cli' et 'zip') ! /!\ "
read -p "Choix (y ou n) : " answer
echo ""

if [ $answer = "y" ]
then
	# Demande du nom d'utilisateur.
	read -p "Pour le bon déroulement de l'installation des scripts, veuillez taper votre nom d'utilisateur : " name
	echo ""

	# Test pour savoir si le paquet est installé, sinon l'installer.
	if [ -z "$(dpkg -s speedtest-cli 2>/dev/null | grep Status)" ]
	then
		echo "Le paquet 'speectest-cli' n'est pas présent sur le disque et va être installé."
		echo ""
		apt install -y speedtest-cli
		echo ""
	else
		echo "Le paquet 'speedtest-cli' est déjà installé."
		echo ""
	fi

	if [ -z "$(dpkg -s zip 2>/dev/null | grep Status)" ]
	then
		echo "Le paquet 'zip' n'est pas présent sur le disque et va être installé."
		echo ""
		apt install -y zip
		echo ""
	else
		echo "Le paquet 'zip' est déjà installé."
		echo ""
	fi	

	cd Debian/

	chmod +x archive backup disks lat speed update upgrade version
	
	cp archive backup disks lat speed update upgrade version /usr/bin/

	# Vérification de la version de Linux.
	if [ -z "$(lsb_release -a 2>/dev/null | grep Debian)" ]
	then
		echo "Abandon de l'installation."
		exit 1
	else
		cd Install\ Firefox/
		
		if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
		then
			echo "Le dossier d'icônes de firefox existe déjà."
			echo ""
		else
			echo "Le dossier d'icônes de firefox n'existe pas et va être créé."
			echo ""
			mkdir /home/"$name"/Images/.firefox_quantum_icons/
			
			if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
			then
				echo "Le dossier à bien été créé."
				echo ""
			fi
		fi

		chmod +x get-firefox remove-firefox-install-package restore-firefox-esr update-firefox      
		
		cp Icon\ Pack/firefox-esr-16.png /home/"$name"/Images/.firefox_quantum_icons/
		cp Icon\ Pack/firefox-esr-symbolic.svg /home/"$name"/Images/.firefox_quantum_icons/
		cp Icon\ Pack/firefox-esr-32.png /home/"$name"/Images/.firefox_quantum_icons/
		cp Icon\ Pack/firefox-esr-48.png /home/"$name"/Images/.firefox_quantum_icons/
		cp Icon\ Pack/firefox-esr-64.png /home/"$name"/Images/.firefox_quantum_icons/
		cp Icon\ Pack/firefox-esr-128.png /home/"$name"/Images/.firefox_quantum_icons/
		cp get-firefox remove-firefox-install-package restore-firefox-esr update-firefox /usr/bin/
		
		cd .. && cd ..
		
		if [ -d /home/"$name"/Documents/.firefox_name_files ]
		then
			echo "OK"
			echo ""
		else
			mkdir /home/"$name"/Documents/.firefox_name_files/
	
			if [ -d /home/"$name"/Documents/.firefox_name_files ]
			then
				echo "OK"
				echo ""
			fi
		fi
		
		cp Debian/Install\ Firefox/Name\ File/firefox-esr.desktop /home/"$name"/Documents/.firefox_name_files/
	
		echo "L'installation des scripts est terminée."
		echo ""
		exit 0
	fi

elif [	$answer = "n" ]
then

	read -p "Voulez-vous installer 'archive' (le paquet 'zip' va être installé s'il ne l'est pas déjà) ? (y ou n) : " answer0
	
	if [ $answer0 = "y" ]
	then
		if [ -z "$(dpkg -s zip 2>/dev/null | grep Status)" ]
		then
			echo "Le paquet 'zip' n'est pas présent sur le disque et va être installé."
			echo ""
			apt install -y zip
			echo ""
		else
			echo "Le paquet 'zip' est déjà installé."
			echo ""
		fi		
		cd Debian/
		chmod +x archive
		cp archive /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer0 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'backup' (le paquet 'zip' va être installé s'il ne l'est pas déjà) ? (y ou n) : " answer1
	
	if [ $answer1 = "y" ]
	then
		if [ -z "$(dpkg -s zip 2>/dev/null | grep Status)" ]
		then
			echo "Le paquet 'zip' n'est pas présent sur le disque et va être installé."
			echo ""
			apt install -y zip
			echo ""
		else
			echo "Le paquet 'zip' est déjà installé."
			echo ""
		fi	
		cd Debian/
		chmod +x backup
		cp backup /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer1 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'disks' ? (y ou n) : " answer2

	if [ $answer2 = "y" ]
	then
		cd Debian/
		chmod +x disks
		cp disks /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer2 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'lat' ? (y ou n) : " answer3

	if [ $answer3 = "y" ]
	then
		cd Debian/
		chmod +x lat
		cp lat /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer3 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'speed' (le paquet 'speectest-cli' va être installé s'il ne l'est pas déjà) ? (y ou n) : " answer4

	if [ $answer4 = "y" ]
	then
		if [ -z "$(dpkg -s speedtest-cli 2>/dev/null | grep Status)" ]
		then
			echo "Le paquet 'speectest-cli' n'est pas présent sur le disque et va être installé."
			echo ""
			apt install -y speedtest-cli
			echo ""
		else
			echo "Le paquet speedtest-cli est déjà installé."
			echo ""
		fi	
		cd Debian/
		chmod +x speed
		cp speed /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer4 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'update' ? (y ou n) : " answer5

	if [ $answer5 = "y" ]
	then
		cd Debian/
		chmod +x update
		cp update /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer5 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'upgrade' ? (y ou n) : " answer6

	if [ $answer6 = "y" ]
	then
		cd Debian/
		chmod +x upgrade
		cp upgrade /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer6 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'version' ? (y ou n) : " answer7

	if [ $answer7 = "y" ]
	then
		cd Debian/
		chmod +x version
		cp version /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer7 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'get-firefox' et toutes ses dépendances (Vous devez être sous Debian) ? (y ou n) : " answer8
	echo ""

	if [ $answer8 = "y" ]
	then
		# Vérification de la version de Debian.
		if [ -z "$(lsb_release -a 2>/dev/null | grep Debian)" ]
		then
			echo "Ce script doit être exécuté sur un environnement Debian."
			echo "Abandon de l'installation."
			exit 1
		else
			# Demande du nom d'utilisateur.
			read -p "Pour le bon déroulement de l'installation des scripts, veuillez taper votre nom d'utilisateur : " name
			echo ""
			
			cd Debian/Install\ Firefox/

			if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
			then
				echo "Le dossier d'icônes de firefox existe déjà."
				echo ""
			else
				echo "Le dossier d'icônes de firefox n'existe pas et va être créé."
				echo ""
				mkdir /home/"$name"/Images/.firefox_quantum_icons/
				
				if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
				then
					echo "Le dossier à bien été créé."
					echo ""
				fi
			fi

			chmod +x get-firefox remove-firefox-install-package restore-firefox-esr update-firefox 

			cp Icon\ Pack/firefox-esr-16.png /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-symbolic.svg /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-32.png /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-48.png /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-64.png /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-128.png /home/"$name"/Images/.firefox_quantum_icons/
			cp get-firefox remove-firefox-install-package restore-firefox-esr update-firefox /usr/bin/

			cd .. && cd ..

			if [ -d /home/"$name"/Documents/.firefox_name_files ]
			then
				echo "OK"
				echo ""
			else
		   		mkdir /home/"$name"/Documents/.firefox_name_files/
	
		   		if [ -d /home/"$name"/Documents/.firefox_name_files ]
		  		then
					echo "OK"
					echo ""
				fi
			fi
		
			cp Debian/Install\ Firefox/Name\ File/firefox-esr.desktop /home/"$name"/Documents/.firefox_name_files/
	
			echo "Installé."
			echo ""
		fi
	else [ $answer8 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	echo "L'installation du/des scipt(s) est terminée."
	echo ""
	exit 0
else
	echo "Veuillez taper 'y' ou 'n'."
	echo ""
	./install-scripts
fi
