#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "Langue : FR-fr"
	echo "Nom du script : Installeur de scripts pour Debian"
	echo "Commande : install-scripts"
	echo "Créateur : Kalvez"
	echo "Emplacement : /usr/bin/"
	echo "Date de la dernière version : 22 mars 2018"
	echo "Version : 1.6.0.20180322"
	echo ""
	echo ""
	echo "..::Détails::.."
	echo ""
	echo "Vous devez exécuter ce script en tant qu'utilisateur root."
	echo ""
	echo "Ce script permet d'installer les scripts suivant dans le dossier '/usr/bin/'."
	echo "Ces scripts sont : backup, disks, lat, speed, update, upgrade, version et toute"
	echo "la suite de scripts nécéssaires à l'installation de Firefox Quantum tels que"
	echo "get-firefox, update-firefox, remove-firefox-install-package et restore-firefox."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
	then
   	echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
   	echo ""
   	exit 1
fi

echo ""
echo "..::INSTALLEUR DE SCRIPTS POUR DEBIAN::.."
echo ""

read -p "Voulez-vous installer tous les scripts d'un coup ? (y or n) : " answer
echo ""

if [ $answer = "y" ]
then
	# Demande du nom d'utilisateur.
	read -p "Pour le bon déroulement de l'installation des scripts, veuillez taper votre nom d'utilisateur : " name
	echo ""

	cd Debian/
	
	cp archive backup disks lat speed update upgrade version /usr/bin/
	
	cd Install\ Firefox/
	
	if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
	then
		echo "Le dossier d'icônes de firefox existe déjà."
		echo ""
	else
		echo "Le dossier d'icônes de firefox n'existe pas et va être créé."
		echo ""
		mkdir /home/"$name"/Images/.firefox_quantum_icons/
	    
	    if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
		then
			echo "Le dossier à bien été créé."
			echo ""
		fi
	fi      
    
    cp Icon\ Pack/firefox-esr-16.png /home/"$name"/Images/.firefox_quantum_icons/
    cp Icon\ Pack/firefox-esr-symbolic.svg /home/"$name"/Images/.firefox_quantum_icons/
    cp Icon\ Pack/firefox-esr-32.png /home/"$name"/Images/.firefox_quantum_icons/
    cp Icon\ Pack/firefox-esr-48.png /home/"$name"/Images/.firefox_quantum_icons/
    cp Icon\ Pack/firefox-esr-64.png /home/"$name"/Images/.firefox_quantum_icons/
    cp Icon\ Pack/firefox-esr-128.png /home/"$name"/Images/.firefox_quantum_icons/
    cp get-firefox remove-firefox-install-package restore-firefox-esr update-firefox /usr/bin/
    
    cd .. && cd ..
    
    if [ -d /home/"$name"/Documents/.firefox_name_files ]
    then
    	echo "OK"
    	echo ""
    else
    	mkdir /home/"$name"/Documents/.firefox_name_files/

    	if [ -d /home/"$name"/Documents/.firefox_name_files ]
    	then
    		echo "OK"
    		echo ""
    	fi
    fi
    
    cp Debian/Install\ Firefox/Name\ File/firefox-esr.desktop /home/"$name"/Documents/.firefox_name_files/

    echo "L'installation des scripts est terminée."
    echo ""
    exit 0

elif [	$answer = "n" ]
then

	read -p "Voulez-vous installer 'archive' (version bêta) ? (y or n) : " answer0
	
	if [ $answer0 = "y" ]
	then
		cd Debian/
		cp archive /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer0 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'backup' ? (y or n) : " answer1
	
	if [ $answer1 = "y" ]
	then
		cd Debian/
		cp backup /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer1 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'disks' ? (y ou n) : " answer2

	if [ $answer2 = "y" ]
	then
		cd Debian/
		cp disks /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer2 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'lat' ? (y ou n) : " answer3

	if [ $answer3 = "y" ]
	then
		cd Debian/
		cp lat /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer3 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'speed' ? (y ou n) : " answer4

	if [ $answer4 = "y" ]
	then
		cd Debian/
		cp speed /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer4 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'update' ? (y ou n) : " answer5

	if [ $answer5 = "y" ]
	then
		cd Debian/
		cp update /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer5 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'upgrade' ? (y ou n) : " answer6

	if [ $answer6 = "y" ]
	then
		cd Debian/
		cp upgrade /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer6 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'version' ? (y ou n) : " answer7

	if [ $answer7 = "y" ]
	then
		cd Debian/
		cp version /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer7 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'get-firefox' et toutes ses dépendances ? (y ou n) : " answer8
	echo

	if [ $answer8 = "y" ]
	then
		# Demande du nom d'utilisateur.
		read -p "Pour le bon déroulement de l'installation des scripts, veuillez taper votre nom d'utilisateur : " name
		echo ""
		
		cd Debian/Install\ Firefox/
		if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
		then
			echo "Le dossier d'icônes de firefox existe déjà."
			echo ""
		else
			echo "Le dossier d'icônes de firefox n'existe pas et va être créé."
			echo ""
			mkdir /home/"$name"/Images/.firefox_quantum_icons/
		    
		    if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
			then
				echo "Le dossier à bien été créé."
				echo ""
			fi
		fi
    	cp Icon\ Pack/firefox-esr-16.png /home/"$name"/Images/.firefox_quantum_icons/
    	cp Icon\ Pack/firefox-esr-symbolic.svg /home/"$name"/Images/.firefox_quantum_icons/
    	cp Icon\ Pack/firefox-esr-32.png /home/"$name"/Images/.firefox_quantum_icons/
    	cp Icon\ Pack/firefox-esr-48.png /home/"$name"/Images/.firefox_quantum_icons/
    	cp Icon\ Pack/firefox-esr-64.png /home/"$name"/Images/.firefox_quantum_icons/
    	cp Icon\ Pack/firefox-esr-128.png /home/"$name"/Images/.firefox_quantum_icons/
    	cp get-firefox remove-firefox-install-package restore-firefox-esr update-firefox /usr/bin/

    	cd .. && cd ..

    	if [ -d /home/"$name"/Documents/.firefox_name_files ]
    	then
    		echo "OK"
    		echo ""
    	else
    		mkdir /home/"$name"/Documents/.firefox_name_files/

    		if [ -d /home/"$name"/Documents/.firefox_name_files ]
    		then
    			echo "OK"
    			echo ""
    		fi
    	fi
    
	    cp Debian/Install\ Firefox/Name\ File/firefox-esr.desktop /home/"$name"/Documents/.firefox_name_files/

		echo "Installé."
		echo ""
	else [ $answer8 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	echo "L'installation du/des scipt(s) est terminée."
	echo ""
	exit 0
else
	echo "Veuillez taper 'y' ou 'n'."
	echo ""
	./install-scripts
fi
