#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
        echo "Langue : FR-fr" 
        echo "Nom du script : Get Firefox"
        echo "Commande : get-firefox"
        echo "Créateur : Kalvez"
        echo "Emplacement : /usr/bin/"
        echo "Date de la dernière version : 22 mars 2018"
        echo "Version : 1.8.0.20180322"
        echo ""
        echo ""
        echo "..::Détails::.."
        echo ""
        echo "Ce script permet de télécharger et d'installer Firefox Quantum, et de remplacer Firefox ESR par celui-ci."
	echo "Il change aussi les icônes de Firefox ESR par les icônes de base de Firefox Quantum, et de supprimer le"
	echo "paquet d'installation de Quantum stocké sur le disque."
        echo ""
        exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
then
        echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
        echo ""
        exit 1
fi

# Demande du nom d'utilisateur.
read -p "Pour le bon déroulement de l'installation de Mozilla Firefox Quantum, veuillez taper votre nom d'utilisateur : " name
echo ""

# Commandes téléchageant et installant le navigateur Firefox Quantum.
wget -O FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
mkdir /opt/firefox
tar xjf FirefoxSetup.tar.bz2 -C /opt/firefox/
mv /usr/lib/firefox-esr/firefox-esr /usr/lib/firefox-esr/firefox-esr_orig 2>/dev/null
ln -s /opt/firefox/firefox/firefox /usr/lib/firefox-esr/firefox-esr

# Changement des icônes de Firefox.
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-16.png /usr/share/icons/hicolor/16x16/apps/firefox-esr.png
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-symbolic.svg /usr/share/icons/hicolor/symbolic/apps/firefox-esr-symbolic.svg
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-32.png /usr/share/icons/hicolor/32x32/apps/firefox-esr.png
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-48.png /usr/share/icons/hicolor/48x48/apps/firefox-esr.png
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-64.png /usr/share/icons/hicolor/64x64/apps/firefox-esr.png
cp /home/"$name"/Images/.firefox_quantum_icons/firefox-esr-128.png /usr/share/icons/hicolor/128x128/apps/firefox-esr.png

# Changement des noms de Firefox ESR vers Firefox Quantum.
mv /usr/share/applications/firefox-esr.desktop /usr/share/applications/firefox-esr.desktop.old
cp /home/"$name"/Documents/.firefox_name_files/firefox-esr.desktop /usr/share/applications/

# Suppression du paquet d'installation de Firefox Quantum.
remove-firefox-install-package
echo ""
echo "Le navigateur Mozilla Firefox Quantum a été installé avec succès."
echo ""
