#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "Langue : FR-fr"
	echo "Nom du script : Remove Firefox Installation Package"
	echo "Commande : backup"
	echo "Créateur : Kalvez"
	echo "Emplacement : /usr/bin/"
	echo "Date de la dernière version : 05 mars 2018"
	echo "Version : 1.1.2.20180305"
	echo ""
	echo ""
	echo "..::Détails::.."
	echo ""
	echo "Ce script permet de supprimer le fichier d'installation de Firefox Quantum. Il s'éxécute automatiquement"
	echo "lorsequ'il es couplé à un autre script tel que 'get-firefox' ou 'update-firefox'."
	echo ""
	exit 0
fi

# Commande supprimant le paquet d'installation de Firefox Quantum.
rm FirefoxSetup.tar.bz2
echo ""
echo "Le paquet d'installation de Firefox à été supprimé du disque avec succès."
echo ""
