#!/bin/sh

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
	then
	echo "Vous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
	echo ""
	exit 1
fi

# Mise à zéro des arguments.
name=0
answer=0
answer0=0
answer1=0
answer2=0
answer3=0
answer4=0
answer5=0
answer6=0
answer7=0
answer8=0
answer9=0
answer10=0
answer11=0

echo "Souhaitez-vous installer tous les scripts d'un coup ('y'), ou choisir individuellement les scripts à installer ('n') ?"
echo "\e[31m\e[1m/!\ ATTENTION : Ceci ('y') entraînera l'installation automatique des paquets nécessaires ('pv', 'dislocker', 'speedtest-cli' et 'zip') ! /!\  \e[0m"
read -p "Choix (y ou n) : " answer
echo ""

if [ $answer = "y" ]
then
	# Demande du nom d'utilisateur.
	read -p "Pour le bon déroulement de l'installation des scripts, veuillez taper votre nom d'utilisateur : " name
	echo ""

	# Test pour savoir si le paquet est installé, sinon l'installer.
	if [ -z "$(dpkg -s speedtest-cli 2>/dev/null | grep Status)" ]
	then
		echo "Le paquet 'speectest-cli' n'est pas présent sur le disque et va être installé."
		echo ""
		apt install -y speedtest-cli
		echo ""
	else
		echo "Le paquet 'speedtest-cli' est déjà installé."
		echo ""
	fi

	if [ -z "$(dpkg -s zip 2>/dev/null | grep Status)" ]
	then
		echo "Le paquet 'zip' n'est pas présent sur le disque et va être installé."
		echo ""
		apt install -y zip
		echo ""
	else
		echo "Le paquet 'zip' est déjà installé."
		echo ""
	fi

	if [ -z "$(dpkg -s dislocker 2>/dev/null | grep Status)" ]
	then
		echo "Le paquet 'dislocker' n'est pas présent sur le disque et va être installé."
		echo ""
		apt install -y dislocker
		echo ""
	else
		echo "Le paquet 'dislocker' est déjà installé."
		echo ""
	fi

	if [ -z "$(dpkg -s pv 2>/dev/null | grep Status)" ]
	then
		echo "Le paquet 'pv' n'est pas présent sur le disque et va être installé."
		echo ""
		apt install -y pv
		echo ""
	else
		echo "Le paquet 'pv' est déjà installé."
		echo ""
	fi

	cd Scripts/

	chmod +x archive backup disks infos lat speed unlocker update update-git upgrade

	# Vérification et remplacement de 'version' par 'infos' si besoin est.
	if [ -f /usr/bin/version ]
	then
		rm /usr/bin/version
		cp archive backup disks infos lat speed unlocker update update-git upgrade /usr/bin/
	else
		cp archive backup disks infos lat speed unlocker update update-git upgrade /usr/bin/
	fi

	cd Install\ Firefox/

	if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
	then
		echo "Le dossier d'icônes de firefox existe déjà."
		echo ""
	else
		echo "Le dossier d'icônes de firefox n'existe pas et va être créé."
		echo ""
		mkdir /home/"$name"/Images/.firefox_quantum_icons/

		if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
		then
			echo "Le dossier à bien été créé."
			echo ""
		fi
	fi

	chmod +x get-firefox remove-firefox-install-package restore-firefox-esr update-firefox

	cp Icon\ Pack/firefox-esr-16.png /home/"$name"/Images/.firefox_quantum_icons/
	cp Icon\ Pack/firefox-esr-symbolic.svg /home/"$name"/Images/.firefox_quantum_icons/
	cp Icon\ Pack/firefox-esr-32.png /home/"$name"/Images/.firefox_quantum_icons/
	cp Icon\ Pack/firefox-esr-48.png /home/"$name"/Images/.firefox_quantum_icons/
	cp Icon\ Pack/firefox-esr-64.png /home/"$name"/Images/.firefox_quantum_icons/
	cp Icon\ Pack/firefox-esr-128.png /home/"$name"/Images/.firefox_quantum_icons/
	cp get-firefox remove-firefox-install-package restore-firefox-esr update-firefox /usr/bin/

	cd .. && cd ..

	if [ -d /home/"$name"/Documents/.firefox_name_files ]
	then
		echo "OK"
		echo ""
	else
		mkdir /home/"$name"/Documents/.firefox_name_files/

		if [ -d /home/"$name"/Documents/.firefox_name_files ]
		then
			echo "OK"
			echo ""
		fi
	fi

	cp Scripts/Install\ Firefox/Name\ File/firefox-esr.desktop /home/"$name"/Documents/.firefox_name_files/

	echo "L'installation des scripts est terminée."
	echo ""
	exit 0

elif [ $answer = "n" ]
then

	read -p "Voulez-vous installer 'archive' (les paquets 'zip' & 'pv' vont être installés s'ils ne le sont pas déjà) ? (y ou n) : " answer0

	if [ $answer0 = "y" ]
	then
		if [ -z "$(dpkg -s zip 2>/dev/null | grep Status)" ]
		then
			echo "Le paquet 'zip' n'est pas présent sur le disque et va être installé."
			echo ""
			apt install -y zip
			echo ""
		else
			echo "Le paquet 'zip' est déjà installé."
			echo ""
		fi

		if [ -z "$(dpkg -s pv 2>/dev/null | grep Status)" ]
		then
			echo "Le paquet 'pv' n'est pas présent sur le disque et va être installé."
			echo ""
			apt install -y pv
			echo ""
		else
			echo "Le paquet 'pv' est déjà installé."
			echo ""
		fi

		cd Scripts/
		chmod +x archive
		cp archive /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer0 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'backup' (les paquets 'zip' & 'pv' vont être installés s'ils ne le sont pas déjà) ? (y ou n) : " answer1

	if [ $answer1 = "y" ]
	then
		if [ -z "$(dpkg -s zip 2>/dev/null | grep Status)" ]
		then
			echo "Le paquet 'zip' n'est pas présent sur le disque et va être installé."
			echo ""
			apt install -y zip
			echo ""
		else
			echo "Le paquet 'zip' est déjà installé."
			echo ""
		fi

		if [ -z "$(dpkg -s pv 2>/dev/null | grep Status)" ]
		then
			echo "Le paquet 'pv' n'est pas présent sur le disque et va être installé."
			echo ""
			apt install -y pv
			echo ""
		else
			echo "Le paquet 'pv' est déjà installé."
			echo ""
		fi

		cd Scripts/
		chmod +x backup
		cp backup /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer1 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'disks' ? (y ou n) : " answer2

	if [ $answer2 = "y" ]
	then
		cd Scripts/
		chmod +x disks
		cp disks /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer2 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	if [ -f /usr/bin/version ]
	then
		read -p "Voulez-vous remplacer 'version' par 'infos' ? (y ou n) : " answer3

		if [ $answer3 = "y" ]
		then
			rm /usr/bin/version
			cd Scripts/
			chmod +x infos
			cp infos /usr/bin/
			echo "Installé."
			echo ""
			cd ..
		else [ $answer3 = "n" ]
			echo "Non-installé."
			echo ""
		fi
	else
		read -p "Voulez-vous installer 'infos' ? (y ou n) : " answer4

		if [ $answer4 = "y" ]
		then
			cd Scripts/
			chmod +x infos
			cp infos /usr/bin/
			echo "Installé."
			echo ""
			cd ..
		else [ $answer4 = "n" ]
			echo "Non-installé."
			echo ""
		fi
	fi

	read -p "Voulez-vous installer 'lat' ? (y ou n) : " answer5

	if [ $answer5 = "y" ]
	then
		cd Scripts/
		chmod +x lat
		cp lat /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer5 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'speed' (le paquet 'speectest-cli' va être installé s'il ne l'est pas déjà) ? (y ou n) : " answer6

	if [ $answer6 = "y" ]
	then
		if [ -z "$(dpkg -s speedtest-cli 2>/dev/null | grep Status)" ]
		then
			echo "Le paquet 'speectest-cli' n'est pas présent sur le disque et va être installé."
			echo ""
			apt install -y speedtest-cli
			echo ""
		else
			echo "Le paquet speedtest-cli est déjà installé."
			echo ""
		fi
		cd Scripts/
		chmod +x speed
		cp speed /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer6 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'unlocker' (le paquet 'dislocker' va être installé s'il ne l'est pas déjà) ? (y ou n) : " answer7

	if [ $answer7 = "y" ]
	then
		if [ -z "$(dpkg -s dislocker 2>/dev/null | grep Status)" ]
		then
			echo "Le paquet 'dislocker' n'est pas présent sur le disque et va être installé."
			echo ""
			apt install -y dislocker
			echo ""
		else
			echo "Le paquet 'dislocker' est déjà installé."
			echo ""
		fi
		cd Scripts/
		chmod +x unlocker
		cp unlocker /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer7 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'update' ? (y ou n) : " answer8

	if [ $answer8 = "y" ]
	then
		cd Scripts/
		chmod +x update
		cp update /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer8 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'update-git' ? (y ou n) : " answer9

	if [ $answer9 = "y" ]
	then
		cd Scripts/
		chmod +x update-git
		cp update-git /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer9 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'upgrade' ? (y ou n) : " answer10

	if [ $answer10 = "y" ]
	then
		cd Scripts/
		chmod +x upgrade
		cp upgrade /usr/bin/
		echo "Installé."
		echo ""
		cd ..
	else [ $answer10 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	read -p "Voulez-vous installer 'get-firefox' et toutes ses dépendances (Vous devez être sous Debian) ? (y ou n) : " answer11
	echo ""

	if [ $answer11 = "y" ]
	then
		# Demande du nom d'utilisateur.
		read -p "Pour le bon déroulement de l'installation des scripts, veuillez taper votre nom d'utilisateur : " name
		echo ""

		cd Scripts/Install\ Firefox/

		if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
		then
			echo "Le dossier d'icônes de firefox existe déjà."
			echo ""
		else
			echo "Le dossier d'icônes de firefox n'existe pas et va être créé."
			echo ""
			mkdir /home/"$name"/Images/.firefox_quantum_icons/

			if [ -d /home/"$name"/Images/.firefox_quantum_icons ]
			then
				echo "Le dossier à bien été créé."
				echo ""
			fi

			chmod +x get-firefox remove-firefox-install-package restore-firefox-esr update-firefox

			cp Icon\ Pack/firefox-esr-16.png /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-symbolic.svg /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-32.png /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-48.png /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-64.png /home/"$name"/Images/.firefox_quantum_icons/
			cp Icon\ Pack/firefox-esr-128.png /home/"$name"/Images/.firefox_quantum_icons/
			cp get-firefox remove-firefox-install-package restore-firefox-esr update-firefox /usr/bin/

			cd .. && cd ..

			if [ -d /home/"$name"/Documents/.firefox_name_files ]
			then
				echo "OK"
				echo ""
			else
		  	mkdir /home/"$name"/Documents/.firefox_name_files/

		   	if [ -d /home/"$name"/Documents/.firefox_name_files ]
		  	then
					echo "OK"
					echo ""
				fi
			fi

			cp Scripts/Install\ Firefox/Name\ File/firefox-esr.desktop /home/"$name"/Documents/.firefox_name_files/

			echo "Installé."
			echo ""
		fi
	else [ $answer11 = "n" ]
		echo "Non-installé."
		echo ""
	fi

	echo "L'installation du/des scipt(s) est terminée."
	echo ""
	exit 0
else
	echo "Veuillez taper 'y' ou 'n'."
	echo ""
	./install-scripts
fi
