#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m**********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATIONS    *\e[0m"
	echo "\e[32m\e[1m**********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLangue:\e[0m        FR-fr"
	echo "\e[32m\e[1mNom du script:\e[0m Archive"
	echo "\e[32m\e[1mCommande:\e[0m      archive [dossier/fichier] [dossier/fichier] [dossier/fichier] ..."
	echo "\e[32m\e[1mCréateur:\e[0m      Kalvez"
	echo "\e[32m\e[1mEmplacement:\e[0m   /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m       0.5.0.20200507-beta"
	echo ""
	echo "\e[32m\e[1m*****************\e[0m"
	echo "\e[32m\e[1m*    DÉTAILS    *\e[0m"
	echo "\e[32m\e[1m*****************\e[0m"
	echo ""
	echo "Ce script, qui ne demande aucun privilèges particulier, permet d'archiver dans des fichiers '.tar' ce que vous souhaitez, que ça soit des dossiers ou des fichiers.\nIl vous demandera alors un nom d'archive, alors il enregistrera l'archive au format suivant : 'archive_nom_année-mois-jour.tar'."
	echo ""
	exit 0
fi

# Déclaration des arguments.
args=0
files=$#

# Bandeau
echo "\e[32m\e[1m*****************\e[0m"
echo "\e[32m\e[1m*    ARCHIVE    *\e[0m"
echo "\e[32m\e[1m*****************\e[0m"
echo ""

# Lecture du nom donné à l'archive.
read -p "Nom de l'archive: " name
echo ""

# Script permettant d'archiver les fichiers et les dossiers dans une archive '.tar'.
for args in $*
do
	FICDOC=$1
	echo "Files or folders being archived : ${FICDOC}"
	echo ""
	if [ -f "${FICDOC}" ] || [ -d "${FICDOC}" ]
	then
		tar -c --use-compress-program=pigz -vf archive_"${name}"_$(date +%Y-%m-%d).tar "${FICDOC}" | pv -ptW >/dev/null
		echo ""
	else
		echo "Le file/folder ${FICDOC} does not exists."
		exit 1
	fi
	shift $(( args = ${args} + 1 )) 2>/dev/null
done
