#!/bin/sh

Help()
{
	echo "\e[32m\e[1m======================\e[0m"
	echo "\e[32m\e[1m=    Informations    =\e[0m"
	echo "\e[32m\e[1m======================\e[0m\n"
	echo "\e[32m\e[1mLangue:\e[0m        FR-fr"
	echo "\e[32m\e[1mNom du script:\e[0m Disks"
	echo "\e[32m\e[1mCommande:\e[0m      disks"
	echo "\e[32m\e[1mCréateur:\e[0m      Kalvez"
	echo "\e[32m\e[1mEmplacement:\e[0m   /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m       1.4.0.20200506\n"
	echo "\e[32m\e[1m=================\e[0m"
	echo "\e[32m\e[1m=    Détails    =\e[0m"
	echo "\e[32m\e[1m=================\e[0m\n"
	echo "Vous devez exécuter ce script en tant qu'utilisateur root si vous voulez avoir accès à l'affichage avancé.\n"
	echo "Ce script permet d'afficher tous les disques (internes, externes et partitions) et les périphériques amovibles connectés sur l'ordinateur ainsi que l'espace disque total et restant.\nLes arguments '-a' ou '--advanced' affichent la liste avancée des disques.\n"
	exit 0
}

Advanced()
{
	echo "\e[32m\e[1m================\e[0m"
	echo "\e[32m\e[1m=    Avancé    =\e[0m"
	echo "\e[32m\e[1m================\e[0m\n"
	fdisk -l
}

Basic()
{
	df -h
}

echo "\e[31m\e[1m***************\e[0m"
echo "\e[31m\e[1m*    DISKS    *\e[0m"
echo "\e[31m\e[1m***************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
elif [ $1 = "-a" 2>/dev/null ] || [ $1 = "--advanced" 2>/dev/null ]
then
	if [ "$(id -u)" != "0" ]
	then
		echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m\n" 1>&2
		exit 1
	else
		Advanced
	fi
else
	Basic
fi
