#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m**********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATIONS    *\e[0m"
	echo "\e[32m\e[1m**********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLangue:\e[0m        FR-fr"
	echo "\e[32m\e[1mNom du script:\e[0m Lat (pour 'Latency')"
	echo "\e[32m\e[1mCommande:\e[0m      lat"
	echo "\e[32m\e[1mCréateur:\e[0m      Kalvez"
	echo "\e[32m\e[1mEmplacement:\e[0m   /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m       1.0.5.20191021"
	echo ""
	echo "\e[32m\e[1m*****************\e[0m"
	echo "\e[32m\e[1m*    DÉTAILS    *\e[0m"
	echo "\e[32m\e[1m*****************\e[0m"
	echo ""
	echo "Ce script permet d'afficher le délai de réponse entre la machine et le DNS de Google."
	echo ""
	exit 0
fi

echo "\e[32m\e[1m*************\e[0m"
echo "\e[32m\e[1m*    LAT    *\e[0m"
echo "\e[32m\e[1m*************\e[0m"
echo ""

# Commande de ping.
ping 8.8.8.8
