#!/bin/sh

Help()
{
	echo "\e[32m\e[1m======================\e[0m"
	echo "\e[32m\e[1m=    Informations    =\e[0m"
	echo "\e[32m\e[1m======================\e[0m\n"
	echo "\e[32m\e[1mLangue:\e[0m        FR-fr"
	echo "\e[32m\e[1mNom du script:\e[0m Unlocker"
	echo "\e[32m\e[1mCommande:\e[0m      unlocker"
	echo "\e[32m\e[1mCréateur:\e[0m      Kalvez"
	echo "\e[32m\e[1mEmplacement:\e[0m   /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m       1.3.0.20201119\n"
	echo "\e[32m\e[1m=================\e[0m"
	echo "\e[32m\e[1m=    Détails    =\e[0m"
	echo "\e[32m\e[1m=================\e[0m\n"
	echo "Vous devez exécuter ce script en tant qu'utilisateur root.\n"
	echo "Ce script permet de déverrouiller des lecteurs chiffrés avec Bitlocker en utilisant le paquet 'Disclocker'.\nCe script donnera un accès en lecture seule au lecteur déverrouillé.\n"
	exit 0
}

Confirmation()
{
	if [ $answer = "o" ] || [ $answer = "O" ]
		then
      echo "\e[31m\e[1m/!\ Le périphérique décrypté va être démonté. Toute activité non-sauvegardée sera perdue. /!\\e[0m\n"
			read -p "Appuyez sur une touche pour continuer..." push1
      umount /media/"$name"/mount && umount /media/"$name"/bitlocker
      echo "\nLe dossier et le lecteur ont été démontés.\n"
      exit 0
	elif [ $answer = "n" ] || [ $answer = "N" ]
		then
      echo "Le dossier et le lecteur sont toujours montés.\nPour les démonter, tapez les commandes suivantes : 'sudo umount /media/"$name"/mount && sudo umount /media/"$name"/bitlocker'\n"
      exit 0
	else
			echo "Veuillez taper 'o' ou 'n'.\n"
	fi
}

Unlock()
{
	echo ""
	read -p "Entrez le chemin du périphérique à décrypter : " path
	dislocker -V "$path" -u -- /media/"$name"/bitlocker
	mount -w -o loop /media/"$name"/bitlocker/dislocker-file /media/"$name"/mount
	Relock
}

Verification()
{
	if [ -d /media/"$name"/bitlocker ]
	then
		if [ -d /media/"$name"/mount ]
		then
			Unlock
		else
			mkdir /media/"$name"/mount
			Unlock
		fi
	else
		mkdir /media/"$name"/bitlocker
		if [ -d /media/"$name"/mount ]
		then
			Unlock
		else
			mkdir /media/"$name"/mount
			Unlock
		fi
	fi
}

Relock()
{
	echo ""
	read -p "Appuyez sur une touche pour continuer..." push0
	echo ""

	while [ $answer != "o" ] || [ $answer != "O" ] || [ $answer != "n" ] || [ $answer != "N" ] || [ -z $answer ]
	do
		read -p "Le script va maintenant démonter le périphérique et le dossier 'Bitlocker', voulez-vous continuer ? ('o' ou 'n') : " answer
		echo ""
		if [ $answer = "o" ] || [ $answer = "n" ]
		then
			break
		fi
	done

	if [ $answer = "o" ] || [ $answer = "O" ] || [ $answer = "n" ] || [ $answer = "N" ]
	then
		Confirmation
	else
		echo "Une erreur inattendue est survenue.\n"
	fi
}

answer=0

echo "\e[31m\e[1m******************\e[0m"
echo "\e[31m\e[1m*    UNLOCKER    *\e[0m"
echo "\e[31m\e[1m******************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	if [ "$(id -u)" != "0" ]
		then
	   	echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m\n" 1>&2
	   	exit 1
		else
			read -p "Veuillez taper votre nom d'utilisateur : " name
			Verification
	fi
fi
