#!/bin/sh

Help()
{
  echo "\e[32m\e[1m======================\e[0m"
  echo "\e[32m\e[1m=    Informations    =\e[0m"
  echo "\e[32m\e[1m======================\e[0m\n"
  echo "\e[32m\e[1mLangue:\e[0m         FR-fr"
  echo "\e[32m\e[1mNom du script:\e[0m  Update"
  echo "\e[32m\e[1mCommande:\e[0m       update"
  echo "\e[32m\e[1mCréateur:\e[0m       Kalvez"
  echo "\e[32m\e[1mEmplacement:\e[0m    /usr/bin/"
  echo "\e[32m\e[1mVersion:\e[0m        1.6.1.20201125"
  echo "\e[32m\e[1m=================\e[0m"
  echo "\e[32m\e[1m=    Détails    =\e[0m"
  echo "\e[32m\e[1m=================\e[0m\n"
  echo "Vous devez exécuter ce script en tant qu'utilisateur root.\n"
  echo "Ce script permet de mettre à jour les dépôts et les paquets des logiciels installés.\nIl nettoie aussi le cache des mises à jour et les paquets inutilisés.\n"
  exit 0
}

Update()
{
  apt-get -y update
  apt-get -y full-upgrade
  apt-get clean
  apt-get -y autoremove
  snap refresh
  if [ "$(dpkg -s flatpak 2>/dev/null | grep Status)" ]
  then
    flatpak update
  else
    echo "\nMise à jour réussie.\n"
    exit 0
  fi
  echo "\nMise à jour réussie.\n"
  exit 0
}

echo "\e[31m\e[1m****************\e[0m"
echo "\e[31m\e[1m*    UPDATE    *\e[0m"
echo "\e[31m\e[1m****************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	if [ "$(id -u)" != "0" ]
		then
	   	echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m\n" 1>&2
	   	exit 1
		else
			Update
	fi
fi
