#!/bin/sh

Help()
{
  echo "\e[32m\e[1m======================\e[0m"
  echo "\e[32m\e[1m=    Informations    =\e[0m"
  echo "\e[32m\e[1m======================\e[0m\n"
  echo "\e[32m\e[1mLangue:\e[0m         FR-fr"
  echo "\e[32m\e[1mNom du script:\e[0m  Update GIT"
  echo "\e[32m\e[1mCommande:\e[0m       update-git"
  echo "\e[32m\e[1mCréateur:\e[0m       Kalvez"
  echo "\e[32m\e[1mEmplacement:\e[0m    /usr/bin/"
  echo "\e[32m\e[1mVersion:\e[0m        1.1.0.20201120\n"
  echo "\e[32m\e[1m=================\e[0m"
  echo "\e[32m\e[1m=    Détails    =\e[0m"
  echo "\e[32m\e[1m=================\e[0m\n"
  echo "Vous devez exécuter ce script en tant qu'utilisateur root.\n"
  echo "Ce script met à jour le dépôt local clôné de 'scripts4linux'.\n"
  exit 0
}

Update()
{
  if [ -d /home/"$name"/scripts4linux ]
  then
    rm -rf /home/"$name"/scripts4linux
    cd /home/"$name"/
    git clone http://github.com/kalvez/scripts4linux.git
    echo ""
  else
    cd /home/"$name"/
  	git clone http://github.com/kalvez/scripts4linux.git
    echo ""
  fi
}

Installation()
{
  if [ $answer = "o" ] || [ $answer = "O" ]
		then
      chmod +x /home/"$name"/scripts4linux/FR-fr/auto-installer
      cd /home/"$name"/scripts4linux/FR-fr && ./auto-installer
      echo ""
      exit 0
	elif [ $answer = "n" ] || [ $answer = "N" ]
		then
      echo "Les scripts ne seront pas mis à jour.\n"
      exit 0
	else
			echo "Veuillez appuyer sur 'o' ou 'n'.\n"
	fi
}

name=0
answer=0

echo "\e[31m\e[1m********************\e[0m"
echo "\e[31m\e[1m*    UPDATE GIT    *\e[0m"
echo "\e[31m\e[1m********************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  Help
fi

if [ "$(id -u)" != "0" ]
  then
    echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m\n" 1>&2
    exit 1
  else
    read -p "Saisissez votre nom d'utilisateur : " name
    echo ""
    Update
    read -p "Voulez-vous mettre les scripts à jour maintenant ? ('o' ou 'n') : " answer
    echo ""
    if [ $answer = "o" ] || [ $answer = "O" ] || [ $answer = "n" ] || [ $answer = "N" ]
    then
      Installation
      echo ""
    else
      echo "Une erreur inattendue est survenue.\n"
    fi
fi
