#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m**********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATIONS    *\e[0m"
	echo "\e[32m\e[1m**********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLangue:\e[0m        FR-fr"
	echo "\e[32m\e[1mNom du script:\e[0m Disks"
	echo "\e[32m\e[1mCommande:\e[0m      disks"
	echo "\e[32m\e[1mCréateur:\e[0m      Kalvez"
	echo "\e[32m\e[1mEmplacement:\e[0m   /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m       1.3.0.20200409"
	echo ""
	echo "\e[32m\e[1m*****************\e[0m"
	echo "\e[32m\e[1m*    DÉTAILS    *\e[0m"
	echo "\e[32m\e[1m*****************\e[0m"
	echo ""
	echo "Vous devez exécuter ce script en tant qu'utilisateur root."
	echo ""
	echo "Ce script permet d'afficher tous les disques (internes, externes et partitions) et les périphériques amovibles connectés sur l'ordinateur ainsi que l'espace disque total et restant.\n Les arguments "-a" ou "--advanced" affichent la liste avancée des disques."
	echo ""
	exit 0
fi

# Choix de l'affichage
if [ $1 = "-a" 2>/dev/null ] || [ $1 = "--advanced" 2>/dev/null ]
then
	# Vérification des privilèges root de l'utilisateur.
	if [ "$(id -u)" != "0" ]
		then
	   	echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m" 1>&2
	   	echo ""
	   	exit 1
	fi
	echo "\e[32m\e[1m***************\e[0m"
	echo "\e[32m\e[1m*    DISKS    *\e[0m"
	echo "\e[32m\e[1m***************\e[0m"
	echo ""

	fdisk -l
else
	echo "\e[32m\e[1m***************\e[0m"
	echo "\e[32m\e[1m*    DISKS    *\e[0m"
	echo "\e[32m\e[1m***************\e[0m"
	echo ""

	df -h
fi
