#!/bin/sh

Help()
{
  echo "\e[32m\e[1m======================\e[0m"
  echo "\e[32m\e[1m=    Informations    =\e[0m"
  echo "\e[32m\e[1m======================\e[0m\n"
  echo "\e[32m\e[1mLangue:\e[0m         FR-fr"
  echo "\e[32m\e[1mNom du script:\e[0m  Upgrade"
  echo "\e[32m\e[1mCommande:\e[0m       upgrade"
  echo "\e[32m\e[1mCréateur:\e[0m       Kalvez"
  echo "\e[32m\e[1mEmplacement:\e[0m    /usr/bin/"
  echo "\e[32m\e[1mVersion:\e[0m        1.3.0.20201120\n"
  echo "\e[32m\e[1m=================\e[0m"
  echo "\e[32m\e[1m=    Détails    =\e[0m"
  echo "\e[32m\e[1m=================\e[0m\n"
  echo "Vous devez exécuter ce script en tant qu'utilisateur root.\n"
  echo "Ce script permet de mettre à jour la distribution linux actuelle.\nIl nettoie le cache de mise à jour et supprime les paquets inutilisés.\n"
  exit 0
}

Upgrade()
{
  apt-get dist-upgrade
  apt-get clean
  apt-get autoremove -y
  echo "\nMise à jour de la distribution Linux réussie.\n"
}

echo "\e[31m\e[1m*****************\e[0m"
echo "\e[31m\e[1m*    UPGRADE    *\e[0m"
echo "\e[31m\e[1m*****************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  Help
else
  if [ "$(id -u)" != "0" ]
    then
      echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m" 1>&2
      exit 1
    else
      Upgrade
  fi
fi
