#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  echo "\e[32m\e[1m**********************\e[0m"
  echo "\e[32m\e[1m*    INFORMATIONS    *\e[0m"
  echo "\e[32m\e[1m**********************\e[0m"
  echo ""
  echo "\e[32m\e[1mLangue:\e[0m         FR-fr"
  echo "\e[32m\e[1mNom du script:\e[0m  Upgrade"
  echo "\e[32m\e[1mCommande:\e[0m       upgrade"
  echo "\e[32m\e[1mCréateur:\e[0m       Kalvez"
  echo "\e[32m\e[1mEmplacement:\e[0m    /usr/bin/"
  echo "\e[32m\e[1mVersion:\e[0m        1.2.2.20191022"
  echo ""
  echo "\e[32m\e[1m*****************\e[0m"
  echo "\e[32m\e[1m*    DÉTAILS    *\e[0m"
  echo "\e[32m\e[1m*****************\e[0m"
  echo ""
  echo "Vous devez exécuter ce script en tant qu'utilisateur root."
  echo ""
  echo "Ce script permet de mettre à jour la distribution linux actuelle.\nIl nettoie le cache de mise à jour et supprime les paquets inutilisés."
  echo ""
  exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
        then
        echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m" 1>&2
        echo ""
        exit 1
fi

echo "\e[32m\e[1m*****************\e[0m"
echo "\e[32m\e[1m*    UPGRADE    *\e[0m"
echo "\e[32m\e[1m*****************\e[0m"
echo ""

# MàJ de la distribution.
apt dist-upgrade

# Nettoyage des paquets inutilisés.
apt clean
apt autoremove -y
echo ""
echo "Mise à jour de la distribution Linux réussie."
echo ""
