#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  echo "\e[32m\e[1m*********************\e[0m"
  echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
  echo "\e[32m\e[1m*********************\e[0m"
  echo ""
  echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
  echo "\e[32m\e[1mScript name:\e[0m Update GIT"
  echo "\e[32m\e[1mCommand:\e[0m     update-git"
  echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
  echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
  echo "\e[32m\e[1mVersion:\e[0m     1.0.2.20200508"
  echo ""
  echo "\e[32m\e[1m****************\e[0m"
  echo "\e[32m\e[1m*    DETAIL    *\e[0m"
  echo "\e[32m\e[1m****************\e[0m"
  echo ""
  echo "You must execute the script with root permissions."
  echo ""
  echo "This script automatically updates the cloned GitHub repo of 'Scripts4Linux'."
  echo ""
  exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
  then
    echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m" 1>&2
    echo ""
    exit 1
fi

echo "\e[32m\e[1m********************\e[0m"
echo "\e[32m\e[1m*    UPDATE GIT    *\e[0m"
echo "\e[32m\e[1m********************\e[0m"
echo ""

# Mise à zéro des arguments.
name=0
answer=0

# Déclaration de la fonction 'INSTALLATION'.
INSTALLATION()
{
	if [ $answer = "y" ] || [ $answer = "Y" ]
		then
      cd /home/"$name"/scripts4linux/EN-uk
      chmod +x auto-installer
      ./auto-installer
      echo ""
      exit
	elif [ $answer = "n" ] || [ $answer = "N" ]
		then
      echo "The scripts won't be updated."
      echo ""
      exit
	else
			echo "Please type 'y' or 'n'."
			echo ""
	fi
}

# Saisie et lecture du nom d'utilisateur.
read -p "Please type your username : " name
echo ""

# Vérification de la présence du dossier 'scripts4linux' sur le disque, et suppression s'il existe, puis clonage du repo GitHub.
if [ -d /home/"$name"/scripts4linux ]
then
  rm -rf /home/"$name"/scripts4linux
  cd /home/"$name"/
  git clone http://github.com/kalvez/scripts4linux.git
  echo ""
else
  cd /home/"$name"/
	git clone http://github.com/kalvez/scripts4linux.git
  echo ""
fi

# Installation des scripts.
read -p "Would you like to update the scripts now ? ('y' or 'n') : " answer
echo ""

if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
then
  INSTALLATION
else
  echo "An unsuspected error has occured."
  echo ""
fi
