#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "**********************"
	echo "*    INFORMATIONS    *"
	echo "**********************"
	echo ""
	echo "Langue:        FR-fr"
	echo "Nom du script: Disks"
	echo "Commande:      disks"
	echo "Créateur:      Kalvez"
	echo "Emplacement:   /usr/bin/"
	echo "Version:       1.3.1.20200506"
	echo ""
	echo "*****************"
	echo "*    DÉTAILS    *"
	echo "*****************"
	echo ""
	echo "Vous devez exécuter ce script en tant qu'utilisateur root si vous voulez avoir accès à l'affichage avancé."
	echo ""
	echo "Ce script permet d'afficher tous les disques (internes, externes et partitions) et les périphériques amovibles connectés sur l'ordinateur ainsi que l'espace disque total et restant.\nLes arguments "-a" ou "--advanced" affichent la liste avancée des disques."
	echo ""
	exit 0
fi

# Choix de l'affichage
if [ $1 = "-a" 2>/dev/null ] || [ $1 = "--advanced" 2>/dev/null ]
then
	# Vérification des privilèges root de l'utilisateur.
	if [ "$(id -u)" != "0" ]
		then
	   	echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
	   	echo ""
	   	exit 1
	fi
	echo "***************"
	echo "*    DISKS    *"
	echo "***************"
	echo ""

	fdisk -l
else
	echo "***************"
	echo "*    DISKS    *"
	echo "***************"
	echo ""

	df -h
fi
