#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
  echo "**********************"
  echo "*    INFORMATIONS    *"
  echo "**********************"
  echo ""
  echo "Langue:         FR-fr"
  echo "Nom du script:  Update"
  echo "Commande:       update"
  echo "Créateur:       Kalvez"
  echo "Emplacement:    /usr/bin/"
  echo "Version:        1.5.5.20191022"
  echo ""
  echo "*****************"
  echo "*    DÉTAILS    *"
  echo "*****************"
  echo ""
  echo "Vous devez exécuter ce script en tant qu'utilisateur root."
  echo ""
  echo "Ce script permet de mettre à jour les dépôts et les paquets des logiciels installés.\nIl nettoie aussi le cache des mises à jour et les paquets inutilisés."
  echo ""
  exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
        then
        echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root." 1>&2
        echo ""
        exit 1
fi

echo "****************"
echo "*    UPDATE    *"
echo "****************"
echo ""

# Mise à jour et confirmation automatique.
pacman -Syu --noconfirm

# Nettoyage des paquets inutilisés.
pacman -Sc --noconfirm && pacman -Scc --noconfirm

# Nettoyage des dépendaces inutilisées
pacman -Qdtq --noconfirm
echo ""
echo "Mise à jour réussie."
echo ""
