#!/bin/sh

Help()
{
	echo "\e[32m\e[1m======================\e[0m"
	echo "\e[32m\e[1m=    INFORMATIONS    =\e[0m"
	echo "\e[32m\e[1m======================\e[0m\n"
	echo "\e[32m\e[1mLangue:\e[0m        FR-fr"
	echo "\e[32m\e[1mNom du script:\e[0m Lat (pour 'Latency')"
	echo "\e[32m\e[1mCommande:\e[0m      lat"
	echo "\e[32m\e[1mCréateur:\e[0m      Kalvez"
	echo "\e[32m\e[1mEmplacement:\e[0m   /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m       1.1.0.20200801\n"
	echo "\e[32m\e[1m=================\e[0m"
	echo "\e[32m\e[1m=    DÉTAILS    =\e[0m"
	echo "\e[32m\e[1m=================\e[0m\n"
	echo "Ce script permet d'afficher le délai de réponse entre la machine et le DNS de Google.\n"
	exit 0
}

Ping()
{
	echo "\e[32m\e[1m==========================\e[0m"
	echo "\e[32m\e[1m=    Ping (DNS Google)   =\e[0m"
	echo "\e[32m\e[1m==========================\e[0m\n"

	ping 8.8.8.8
}

echo "\e[31m\e[1m*************\e[0m"
echo "\e[31m\e[1m*    LAT    *\e[0m"
echo "\e[31m\e[1m*************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	Ping
fi
