#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "*******************"
	echo "..::INFORMATION::.."
	echo "*******************"
	echo ""
	echo "Language:    EN-uk"
	echo "Script name: Infos"
	echo "Command:     infos"
	echo "Author:      Kalvez"
	echo "Location:    /usr/bin/"
	echo "Version:     3.0.3.20191004"
	echo ""
	echo "**************"
	echo "..::DETAIL::.."
	echo "**************"
	echo ""
	echo "You must execute the script with root permissions."
	echo ""
	echo "This script displays a lot of information about the operating system, but also about the specs of the computer and some other pactical data"
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
then
	echo "This script must be executed with root privileges." 1>&2
	echo ""
	exit 1
fi

# Fonction conversion de la RAM en MiB
converterMiB()
{
	mib=1048.576
	memory=0
	memory=$1
	memory=$(echo "$memory/$mib" |bc)
	echo "$memory"
}

# Mise à zéro des arguments.
os_type=0
architecture=0
device_name=0
users=0
uptime=0
kernel_info=0
system_manufacturer=0
system_model=0
device_type=0
screen_resolution=0
cpu_model=0
total_ram=0
available_ram=0
total_swap=0
cached_swap=0
root_part_available=0
root_part_total=0
home_part_available=0
home_part_total=0
baseboard=0
baseboard_version=0
baseboard_serial=0
bios_version=0
bios_date=0
serial=0

# Déclaration des arguments.
os_type=$(uname -o)
architecture=$(uname -i)
device_name=$(uname -n)
users=$(users)
uptime=$(uptime)
kernel_info=$(uname -srv)
system_manufacturer=$(dmidecode -s system-manufacturer)
system_model=$(dmidecode -s system-product-name)
device_type=$(dmidecode -s chassis-type)
screen_resolution=$(xdpyinfo | grep dimensions | awk '{print $2}')
cpu_model=$(dmidecode -s processor-version | uniq)
total_ram=$(grep -Eom1 '[0-9]{1,9}' /proc/meminfo | tail -1	)
total_ram=$(converterMiB $total_ram)
available_ram=$(grep -Eom3 '[0-9]{1,9}' /proc/meminfo | tail -1)
available_ram=$(converterMiB $available_ram)
total_swap=$(grep -Eom15 '[0-9]{1,9}' /proc/meminfo | tail -1)
total_swap=$(converterMiB $total_swap)
cached_swap=$(grep -Eom6 '[0-9]{1,9}' /proc/meminfo | tail -1)
cached_swap=$(converterMiB $cached_swap)
root_part_available=$(df -Ph / | tail -1 | awk '{print $4}')
root_part_total=$(df -Ph / | tail -1 | awk '{print $2}')
home_part_available=$(df -Ph . | tail -1 | awk '{print $4}')
home_part_total=$(df -Ph . | tail -1 | awk '{print $2}')
baseboard=$(dmidecode -s baseboard-product-name)
baseboard_version=$(dmidecode -s baseboard-version)
baseboard_serial=$(dmidecode -s baseboard-serial-number)
bios_version=$(dmidecode -s bios-version)
bios_date=$(dmidecode -s bios-release-date)
serial=$(dmidecode -s system-serial-number)

# Affichage des infos.
echo "****************************"
echo "..::SOFTWARE INFORMATION::.."
echo "****************************"
lsb_release -a
echo "OS Type:        $os_type"
echo "Architecture:   $architecture"
echo "Device Name:    $device_name"
echo "User(s):        $users"
echo "Uptime:        $uptime"
echo "Kernel Version:	$kernel_info"
echo ""
echo "**************************"
echo "..::DEVICE INFORMATION::.."
echo "**************************"
echo "Manufacturer:   $system_manufacturer"
echo "Model:          $system_model"
echo "Device Type:    $device_type"
echo "Screen Res.:    $screen_resolution"
echo "Processor:      $cpu_model"
echo "Free Memory:    $available_ram MiB / $total_ram MiB"
echo "Cached Swap:    $cached_swap MiB / $total_swap MiB"
echo "Root Partition: $root_part_available"B" / $root_part_total"B" Available"
echo "Home Partition: $home_part_available"B" / $home_part_total"B" Available"
echo "Baseboard:      $baseboard | $baseboard_version"
echo "Baseboard S/N:  $baseboard_serial"
echo "BIOS Version:   $bios_version | $bios_date"
echo "Device S/N:     $serial"
echo ""
