#!/bin/sh

Help()
{
	echo "\e[32m\e[1m=====================\e[0m"
	echo "\e[32m\e[1m=    Information    =\e[0m"
	echo "\e[32m\e[1m=====================\e[0m\n"
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Backup"
	echo "\e[32m\e[1mCommand:\e[0m     backup"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.8.O.20200731\n"
	echo "\e[32m\e[1m================\e[0m"
	echo "\e[32m\e[1m=    Detail    =\e[0m"
	echo "\e[32m\e[1m================\e[0m\n"
	echo "You must execute the script with root permissions.\n"
	echo "This script permits to backup the following folders : 'Documents', 'Pictures' and 'Download' in a '.tar' archive automatically named 'backup' and dated according to the date of the day.\nOnce the archive is created, it's placed in the 'Backups' folder located in your personnal folder.\nIf it's not present on the disk, it will automatically be created is the user folder. In your case, this will be in the '/home/$USER/' folder.\nThis script is using the '.tar' archive format which is a proprietary format. However, if you want to modify the backupped folder in the archive, you can edit that script at the line 41 and put whatever you want to backup respecting the spaces between each argument.\nTo restore a backup, you have to create the 'Backups' folder in the root of your personal folder, if it does not already exists, and place the backup archive in it.\n"
	exit 0
}

Choice()
{
	echo "\n\e[32m\e[1m=======================\e[0m"
	echo "\e[32m\e[1mWhat do you want to do?\e[0m"
	echo "\e[32m\e[1m=======================\e[0m\n"
	echo "1 - Backup"
	echo "2 - Restore\n"
	echo "3 - Exit\n"
	read -p "Your answer : " statement

	if [ $statement = "1" ]
	then
		if [ -d /home/"$name"/Backups ]
		then
			Backup
		else
			mkdir /home/"$name"/Backups/
			Backup
		fi
	elif [ $statement = "2" ]
	then
		if [ -d /home/"$name"/Backups ]
		then
			Restore
		else
			echo "The 'Backups' folder does not exists on the disk. You have to create the folder and move your previous backup in it or make a backup in order to restore it.\n"
			exit 1
		fi
	elif [ $statement = "3" ]
	then
		echo "\nExiting...\n"
		exit 0
	else
		echo "\nPlease select either '1', '2' or '3'.\n"

		Choice
	fi
}

Backup()
{
	echo "\n\e[32m\e[1m======\e[0m"
	echo "\e[32m\e[1mBackup\e[0m"
	echo "\e[32m\e[1m======\e[0m\n"

	echo "Backup in progress...\n"
	tar -c --use-compress-program=pigz -vf backup_$(date +%Y-%m-%d).tar /home/"$name"/Documents/ /home/"$name"/Pictures/ /home/"$name"/Downloads/ | pv -ptW >/dev/null
	mv backup_$(date +%Y-%m-%d).tar /home/"$name"/Backups/

	echo "\nBackup over!\n"
	exit 0
}

Restore()
{
	echo "\n\e[32m\e[1m=======\e[0m"
	echo "\e[32m\e[1mRestore\e[0m"
	echo "\e[32m\e[1m=======\e[0m\n"

	read -p "Please type the archive date (YYYY-MM-DD) : " archive_date

	echo "\nRestore in progress...\n"
	tar -xvzf /home/"$name"/Backups/backup_"$archive_date".tar -C / | pv -ptW >/dev/null
	sudo chown -R $name: /home/"$name"/

	echo "\nRestore over!\n"
	exit 0
}

name=0
statement=0

echo "\e[31m\e[1m****************\e[0m"
echo "\e[31m\e[1m*    BACKUP    *\e[0m"
echo "\e[31m\e[1m****************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	if [ "$(id -u)" != "0" ]
	then
	 	echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m\n" 1>&2
	 	exit 1
	else
		read -p "Please type your username : " name
		Choice
	fi
fi
