#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m*********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
	echo "\e[32m\e[1m*********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Speed"
	echo "\e[32m\e[1mCommand:\e[0m     speed"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.0.6.20191021"
	echo ""
	echo "\e[32m\e[1m****************\e[0m"
	echo "\e[32m\e[1m*    DETAIL    *\e[0m"
	echo "\e[32m\e[1m****************\e[0m"
	echo ""
	echo "Based on the 'speedtest-cli' package, this script tests your network's internet connection.\nIt has a secure connection (--secure) and uses 'MB' instead of 'Mb' (--bytes)."
	echo ""
	exit 0
fi

echo "\e[32m\e[1m***************\e[0m"
echo "\e[32m\e[1m*    SPEED    *\e[0m"
echo "\e[32m\e[1m***************\e[0m"
echo ""

# Commande appelant speedtest-cli et l'argument remplacant les Bits par des Octets et utilisant une connexion HTTPS.
speedtest --bytes --secure
echo ""
