#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m*********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATION    *\e[0m"
	echo "\e[32m\e[1m*********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLanguage:\e[0m    EN-uk"
	echo "\e[32m\e[1mScript name:\e[0m Unlocker"
	echo "\e[32m\e[1mCommand:\e[0m     unlocker"
	echo "\e[32m\e[1mAuthor:\e[0m      Kalvez"
	echo "\e[32m\e[1mLocation:\e[0m    /usr/bin/"
	echo "\e[32m\e[1mVersion:\e[0m     1.2.0.20191021"
	echo ""
	echo "\e[32m\e[1m****************\e[0m"
	echo "\e[32m\e[1m*    DETAIL    *\e[0m"
	echo "\e[32m\e[1m****************\e[0m"
	echo ""
	echo "You must execute the script with root permissions."
	echo ""
	echo "This script permits to unlock drives that are encrypted with Bitlocker using the 'dislocker' package.\nIt gives a R/W access to the unlocked drive."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
	then
   	echo "\e[31m\e[1mThis script must be executed with root privileges.\e[0m" 1>&2
   	echo ""
   	exit 1
fi

# Déclaration de la variable 'answer' à zéro.
answer="0"

# Déclaration de la fonction 'CONFIRMATION'.
CONFIRMATION()
{
	if [ $answer = "y" ] || [ $answer = "Y" ]
		then
            echo "/!\ The decrypted drive will be unmounted. Any unsaved activity on the drive will be lost. /!\ "
						echo ""
						read -p "Press any key to continue..." push1
            echo ""
            umount /media/"$name"/mount && umount /media/"$name"/bitlocker
            echo "The folder and the drive has been unmounted."
						echo ""
            exit
	elif [ $answer = "n" ] || [ $answer = "N" ]
		then
            echo "The folder and the drive are still mounted."
            echo "To unmount them, please type the following commands : 'sudo umount /media/"$name"/mount && sudo umount /media/"$name"/bitlocker'"
            echo ""
            exit
	else
			echo "Please type 'y' or 'n'."
			echo ""
	fi
}

# Déclaration de la fonction 'UNLOCK'.
UNLOCK()
{
	# Déclaration du chemin du disque à débloquer.
	read -p "Enter the path of the drive to unlock : " path

	# Utilisation de Dislocker pour déverrouiller le disque.
	dislocker -V "$path" -u -- /media/"$name"/bitlocker

	# Montage du disque dans le dossier mount.
	mount -w -o loop /media/"$name"/bitlocker/dislocker-file /media/"$name"/mount
}

echo "\e[32m\e[1m******************\e[0m"
echo "\e[32m\e[1m*    UNLOCKER    *\e[0m"
echo "\e[32m\e[1m******************\e[0m"
echo ""

# Saisie et lecture du nom d'utilisateur.
echo ""
read -p "Please type your username : " name
echo ""

# Vérification de l'existence des dossier 'bitlocker' et 'mount'. S'ils n'existent pas, les créer.
if [ -d /media/"$name"/bitlocker ]
then
	if [ -d /media/"$name"/mount ]
	then
		UNLOCK
		echo ""
	else
		echo "The 'mount' folder does not exists and will be created."
		echo ""
		mkdir /media/"$name"/mount
		UNLOCK
		echo ""
	fi
else
	echo "The 'Bitlocker' folder does not exists and will be created."
	echo ""
	mkdir /media/"$name"/bitlocker
	if [ -d /media/"$name"/mount ]
	then
		UNLOCK
		echo ""
	else
		echo "The 'mount' folder does not exists and will be created."
		echo ""
		mkdir /media/"$name"/mount
		UNLOCK
		echo ""
	fi
fi

# Pause.
echo ""
read -p "Press any key to continue..." push0
echo ""

# Demande de confirmation pour démonter le lecteur et le dossier bitlocker.
while [ $answer != "y" ] || [ $answer != "Y" ] || [ $answer != "n" ] || [ $answer != "N" ] || [ -z $answer ]
do
	read -p "The script will now unmount the drive and the 'Bitlocker' folder, do you want to continue ? (y or n) : " answer
	echo ""
	if [ $answer = 'y' ] || [ $answer = 'n' ]
	then
		break
	fi
done

# Si oui, exécution de CONFIRMATION.
if [ $answer = "y" ] || [ $answer = "Y" ] || [ $answer = "n" ] || [ $answer = "N" ]
then
	CONFIRMATION
else
	echo "An unsuspected error has occured."
fi
