#!/bin/sh

# Onglet d'aide.
if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	echo "\e[32m\e[1m**********************\e[0m"
	echo "\e[32m\e[1m*    INFORMATIONS    *\e[0m"
	echo "\e[32m\e[1m**********************\e[0m"
	echo ""
	echo "\e[32m\e[1mLangue:\e[0m        FR-fr"
	echo "\e[32m\e[1mNom du script:\e[0m Installeur automatique de scripts pour Debian / Kali Linux."
	echo "\e[32m\e[1mCommande:\e[0m      auto-installer"
	echo "\e[32m\e[1mCréateur:\e[0m      Kalvez"
	echo "\e[32m\e[1mEmplacement:\e[0m   scripts4linux/FR-fr/"
	echo "\e[32m\e[1mVersion:\e[0m       2.5.5.20200622"
	echo ""
	echo "\e[32m\e[1m*****************\e[0m"
	echo "\e[32m\e[1m*    DÉTAILS    *\e[0m"
	echo "\e[32m\e[1m*****************\e[0m"
	echo ""
	echo "/!\ Ce script doit être exécuté en tant qu'utilisateur root. /!\ "
	echo ""
	echo "Ce script permet de détecter la distribution de linux sur laquelle il est lancé et donc de choisir en conséquence le bon pack de scripts à installer."
	echo ""
	exit 0
fi

# Vérification des privilèges root de l'utilisateur.
if [ "$(id -u)" != "0" ]
	then
	echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m" 1>&2
	echo ""
	exit 1
fi

echo "\e[32m\e[1m************************\e[0m"
echo "\e[32m\e[1m*    AUTO-INSTALLER    *\e[0m"
echo "\e[32m\e[1m************************\e[0m"
echo ""

# Vérification de la version de Linux.
if [ -z "$(lsb_release -a 2>/dev/null | grep Debian)" ]
then
	if [ -z "$(lsb_release -a 2>/dev/null | grep Raspbian)" ]
	then
		if [ -z "$(lsb_release -a 2>/dev/null | grep Kali)" ]
		then
			if [ -z "$(lsb_release -a 2>/dev/null | grep Ubuntu)" ]
			then
				if [ -z "$(lsb_release -a 2>/dev/null | grep elementary)" ]
				then
					if [ -z "$(lsb_release -a 2>/dev/null | grep LinuxMint)" ]
					then
						if [ -z "$(lsb_release -a 2>/dev/null | grep ManjaroLinux)" ]
						then
							if [ -z "$(lsb_release -a 2>/dev/null | grep Zorin)" ]
							then
								if [ -z "$(lsb_release -a 2>/dev/null | grep Deepin)" ]
								then
									if [ -z "$(lsb_release -a 2>/dev/null | grep Pop)" ]
									then
										echo "Please use an appropriate distro."
									else
										cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
										chmod +x installer
										./installer
										exit 0
									fi
								else
									cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
									chmod +x installer
									./installer
									exit 0
								fi
							else
								cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
								chmod +x installer
								./installer
								exit 0
							fi
						else
							cd Manjaro\ -\ Mandriva/
							chmod +x installer
							./installer
							exit 0
						fi
					else
						cd Linux\ Mint/
						chmod +x installer
						./installer
						exit 0
					fi
				else
					cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
					chmod +x installer
					./installer
					exit 0
				fi
			else
				cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/
				chmod +x installer
				./installer
				exit 0
			fi
		else
			cd Debian\ -\ Kali\ Linux/
			chmod +x installer
			./installer
			exit 0
		fi
	else
		cd Raspbian\
		chmod +x installer
		./installer
		exit 0
	fi
else
  cd Debian\ -\ Kali\ Linux/
  chmod +x installer
  ./installer
  exit 0
fi
