#!/bin/sh

Help()
{
	echo "\e[32m\e[1m======================\e[0m"
	echo "\e[32m\e[1m=    Informations    =\e[0m"
	echo "\e[32m\e[1m======================\e[0m\n"
	echo "\e[32m\e[1mLangue:\e[0m        FR-fr"
	echo "\e[32m\e[1mNom du script:\e[0m Installeur automatique de scripts pour Debian / Kali Linux."
	echo "\e[32m\e[1mCommande:\e[0m      auto-installer"
	echo "\e[32m\e[1mCréateur:\e[0m      Kalvez"
	echo "\e[32m\e[1mEmplacement:\e[0m   scripts4linux/FR-fr/"
	echo "\e[32m\e[1mVersion:\e[0m       2.6.0.20201121\n"
	echo "\e[32m\e[1m=================\e[0m"
	echo "\e[32m\e[1m=    Détails    =\e[0m"
	echo "\e[32m\e[1m=================\e[0m\n"
	echo "/!\ Ce script doit être exécuté en tant qu'utilisateur root. /!\ \n"
	echo "Ce script permet de détecter la distribution de linux sur laquelle il est lancé et donc de choisir en conséquence le bon pack de scripts à installer.\n"
	exit 0
}

fetchDistro()
{
	distributor_id=$(lsb_release -ar 2>/dev/null | grep 'Distributor ID' | awk '{$1=$2=""; print $0}')
	Verification
}

Verification()
{
	if [ $distributor_id = "Debian" ] || [ $distributor_id = "Raspbian" ] || [ $distributor_id = "Kali" ]
	then
	  chmod +x Debian\ -\ Kali\ Linux\ -\ Raspbian/installer
	  cd Debian\ -\ Kali\ Linux/Raspbian/ && ./installer
	  exit 0
	elif [ $distributor_id = "Ubuntu" ] || [ $distributor_id = "elementary" ] || [ $distributor_id = "Zorin" ] || [ $distributor_id = "Deepin" ] || [ $distributor_id = "Pop" ]
	then
		chmod +x Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/installer
		cd Ubuntu\ -\ Lubuntu\ -\ Xubuntu\ -\ elementaryOS\ -\ PopOS\ -\ ZorinOS\ -\ DeepinOS/ && ./installer
		exit 0
	elif [ $distributor_id = "LinuxMint" ]
	then
		chmod +x Linux\ Mint/installer
		cd Linux\ Mint/ && ./installer
		exit 0
	elif [ $distributor_id = "ManjaroLinux" ]
	then
		chmod +x Manjaro\ -\ Mandriva/installer
		cd Manjaro\ -\ Mandriva/ && ./installer
		exit 0
	else
		echo "Cette distribution n'est pas supportée.\n"
		exit 1
	fi
}

distributor_id=0

echo "\e[31m\e[1m************************\e[0m"
echo "\e[31m\e[1m*    AUTO INSTALLER    *\e[0m"
echo "\e[31m\e[1m************************\e[0m\n"

if [ $1 = "-h" 2>/dev/null ] || [ $1 = "--help" 2>/dev/null ]
then
	Help
else
	if [ "$(id -u)" != "0" ]
	then
		echo "\e[31m\e[1mVous n'avez pas les privilèges requis, ce script doit être exécuté en tant qu'utilisateur root.\e[0m\n" 1>&2
		exit 1
	else
		fetchDistro
	fi
fi
